// Created 9/26/2013 8:29:57 PM
(function(){var a=function b(){if(2===arguments.length&&"number"===typeof arguments[0]&&"number"===typeof arguments[1])this.x=arguments[0],this.y=arguments[1];else if(1===arguments.length&&arguments[0].type===b.type)this.x=arguments[0].x,this.y=arguments[0].y;else if(0===arguments.length)this.y=this.x=0;else throw"Arguments must be 2 numbers or nothing at all";},d=a.prototype;a.type="Vector2";d.type=a.type;d.set=function(b,e){if(2===arguments.length&&"number"===typeof arguments[0]&&"number"===typeof arguments[1])this.x=
arguments[0],this.y=arguments[1];else if(1===arguments.length&&arguments[0].type===a.type)this.x=arguments[0].x,this.y=arguments[0].y;else throw'Argument must be 2 numbers or 1 "Vector2"';};d.neg=function(){return new a(-this.x,-this.y)};d.vclone=function(){return new a(this.x,this.y)};d.add=function(b){var e=new a(this.x,this.y);if("number"===typeof b)e.x+=b,e.y+=b;else if(b.type&&b.type===a.type)e.x+=b.x,e.y+=b.y;else throw'Argument must be of type "Vector2" or "number"';return e};d.sub=function(b){var e=
new a(this.x,this.y);if("number"===typeof b)e.x-=b,e.y-=b;else if(b.type&&b.type===a.type)e.x-=b.x,e.y-=b.y;else throw'Argument must be of type "Vector2" or "number"';return e};d.mul=function(b){var e=new a(this.x,this.y);if("number"===typeof b)e.x*=b,e.y*=b;else if(b.type&&b.type===a.type)e.x*=b.x,e.y*=b.y;else throw'Argument must be of type "Vector2" or "number"';return e};d.div=function(b){var e=new a(this.x,this.y);if("number"===typeof b)e.x/=b,e.y/=b;else if(b.type&&b.type===a.type)e.x/=b.x,
e.y/=b.y;else throw'Argument must be of type "Vector2" or "number"';return e};d.dot=function(b){if(!b||!b.type||b.type!==a.type)throw'Arguments must be of type "Vector2"';return this.x*b.x+this.y*b.y};d.square=function(){return new a(this.x*this.x,this.y*this.y)};d.vlength=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};d.abs=function(){return new a(Math.abs(this.x),Math.abs(this.y))};d.map=function(b){var e=new a;e.x=b(this.x);e.y=b(this.y);return e};a.dot=function(b,e){if(b.type!==a.type||
e.type!==a.type)throw'Arguments must be of type "Vector2"';return b.x*e.x+b.y*e.y};a.crossVV=function(b,e){if(b.type!==a.type||e.type!==a.type)throw'Arguments must be of type "Vector2"';return b.x*e.y-b.y*e.x};a.crossVN=function(b,e){if(b.type!==a.type||"number"!==typeof e)throw'Arguments must be of type "Vector2" and "number"';return new a(e*b.y,-e*b.x)};a.crossNV=function(b,e){if("number"!==typeof b||e.type!==a.type)throw'Arguments must be of type "number" and "Vector2"';return new a(-b*e.y,b*e.x)};
d.clip=function(b,e,d,n){var p=new a;p.x=Math.max(b,Math.min(d,this.x));p.y=Math.max(e,Math.min(n,this.y));return p};d.toString=function(){return"("+this.x+","+this.y+")"};window.Vector2=a;d.applyAsPosition=function(a){a.style.left=this.x+"px";a.style.top=this.y+"px"};d.applyAsSize=function(a){a.style.width=this.x+"px";a.style.height=this.y+"px"};d.stretchToMe=function(b,e){var d=new a;d.x=Math[e?"min":"max"](this.x,b*this.y);d.y=d.x/b;return d};d.getCenterPosition=function(a){return this.sub(a).div(2)}})();
var _slow=1;function initSimpleUtils(){var a=navigator.userAgent.toLowerCase();ANDROID40=window.system.platform.android&&-1!=a.indexOf("4.0.");ANDROID3=3==window.system.device.version&&window.system.platform.android;ANDROID2=2==window.system.device.version&&window.system.platform.android;FORCE_FLAT=ANDROID3;DEV_3D=Modernizr.csstransforms3d;DOUBLE_CLICK_TO_ZOOM=!0;UP_SCALE=1}
var DEBUG_SHOW_FOLD_SHADOW=!1,TUNE_FOLD_SCALE_ENABLE=!0,TUNE_MINIMUM_FOLD_SCALE=0.25,TUNE_FOLD_SHADOW_ALPHA=!0,TUNE_FOLD_SHADOW_KOEFF=0.35,TIMEOUT_TO_DO_PRETRANSFORM=60*_slow,TIMEOUT_TO_SET_TRANSITION=60*_slow,TIMEOUT_TO_DO_POSTTRANSFORM=60*_slow,TIMEOUT_AFTER_ALL=60*_slow,TUNE_ZINDEX_SINGLE_CANVAS=-100,Z_INDEX_ADD=350,LAST_Z=-300,Z_STEP=5,FIRST_Z=-100,_debugNC=!1,getBookLength=function(){return publicationData.pageCount};
function SoftPlainFlipElements(a,d,c,b,e,z,n){function p(f,b){g+=1;var c=function(){this.style.webkitTransitionProperty="";this.style.webkitTransitionDuration="";this.removeEventListener("webkitTransitionEnd",c,!1);var f=this;setTimeout(function(){b&&b(f);_debugNC&&console.log(a+times()+"timeout",g,f.id);(g-=1)||setTimeout(function(){n&&n(u);I=!1},TIMEOUT_AFTER_ALL)},TIMEOUT_TO_DO_POSTTRANSFORM)};f.addEventListener("webkitTransitionEnd",c,!1)}function L(){startTime=(new Date).getTime();_debugNC&&
console.log(a+times()+"applyDestinationListen",g);p(v,function(a){e&&e(u)});B(v,k.flipDiv);p(w);B(w,k.contentObject,q+2);l.backgroundDiv!=k.backgroundDiv&&(p(f),B(f,k.backgroundDiv,q+4));s&&(p(s,function(a){}),B(s,k.nextShadow),s.style.opacity="0");m&&r&&(C(m,"end"),p(m,function(a){C(m,"start")}))}function C(a,f){var b="start"==f,d=b?TUNE_MINIMUM_FOLD_SCALE:1,e=z?0:c-A,s=dev_translate((b?A*d:0)*(z?-1:1),0,8),d=TUNE_FOLD_SCALE_ENABLE?dev_scale(d<TUNE_MINIMUM_FOLD_SCALE?TUNE_MINIMUM_FOLD_SCALE:d):"";
TUNE_FOLD_SHADOW_ALPHA&&(a.style.opacity=b?"0":"1");a.style.left=e+"px";a.style.webkitTransformOrigin=String(z?0:A)+"px 0px";a.style.webkitTransform=d+" "+s}function B(a,f,b){var c=void 0==b?a.zOffset||0:b;void 0!=b&&(a.zOffset=b);a.xOffset=f;translate(a,f,c)}function G(a,f){a.zOffset=f;translate(a,a.xOffset||0,f)}function E(){var a={};z?r?(a.flipDiv=0,a.contentObject=0,a.backgroundDiv=-c,a.nextShadow=-x):(a.flipDiv=0,a.contentObject=c,a.backgroundDiv=-c,a.nextShadow=-c):r&&F?(a.flipDiv=0,a.contentObject=
0,a.backgroundDiv=c,a.nextShadow=c):F?(a.flipDiv=0,a.contentObject=-c,a.backgroundDiv=c,a.nextShadow=c):(a.flipDiv=-c,a.contentObject=0,a.backgroundDiv=-c,a.nextShadow=-2*c);return a}this.id=a;var u=this,r=!0,F=!0,x=0.6*c,l=E(),k,K,I,g=0,q=LAST_Z--,A=c*TUNE_FOLD_SHADOW_KOEFF,v=createDiv("flipd"+a,!0);v.style.webkitTransformStyle=ANDROID3||FORCE_FLAT?"flat":"preserve-3d";d.appendChild(v);sizeDiv(v,c,b);G(v,q);var w=createDiv("div"+a);sizeDiv(w,c,b);var D=createCanvas("cc"+a,c,b);w.appendChild(D);w.contentCanvas=
D;D=createDiv("vd"+a,c,b);w.appendChild(D);w.vectorDiv=D;D=createCanvas("tc"+a,c,b);w.appendChild(D);w.topCanvas=D;v.appendChild(w);B(w,l.contentObject,q+2);var f=createBackgroundDiv("backd"+a);sizeDiv(f,c,b);v.appendChild(f);B(f,l.backgroundDiv,q+4);var s=createShadowOnNextDiv("nextsh"+a,z);s&&(d.appendChild(s),sizeDiv(s,x,b),B(s,l.nextShadow,q));var m=createFoldShadow("foldsh"+a,A,b,z);m&&(v.appendChild(m),C(m,"start"));this.flipDiv=v;this.backgroundDiv=f;var y=function(f,b,c){_debugNC&&console.log(a+
"prepare",f.id,g);f.style.webkitTransitionProperty="-webkit-transform "+(c||"");f.style.webkitTransitionTimingFunction="cubic-bezier(0.9,0.05,0.95,1)";f.style.webkitTransitionDuration=String(b*_slow)+"s"};this.id=a;var t=function(){l=E();var a={};z?r&&F?(a.flipDiv=c,a.contentObject=-c,a.backgroundDiv=0,a.nextShadow=c-x):F&&(a.flipDiv=0,a.contentObject=0,a.backgroundDiv=-c,a.nextShadow=-c):r&&F?(a.flipDiv=-c,a.contentObject=c,a.backgroundDiv=0,a.nextShadow=0):F?(a.flipDiv=0,a.contentObject=0,a.backgroundDiv=
c+1,a.nextShadow=c):(a.flipDiv=0,a.contentObject=-c,a.backgroundDiv=0,a.nextShadow=-c);k=a;B(v,l.flipDiv,q);B(w,l.contentObject,q+2);B(f,l.backgroundDiv,q+4);m&&C(m,"start");s&&(B(s,l.nextShadow,q),s.style.opacity="1")},N=function(a){y(v,a);y(w,a);y(f,a);s&&y(s,a,"opacity");m&&r&&y(m,a,TUNE_FOLD_SHADOW_ALPHA?"opacity":"")};this.startAnimation=function(a,f,b,c){I=!0;K=c;r=f;F=b;t();setTimeout(function(){N(a);setTimeout(function(){L()},TIMEOUT_TO_SET_TRANSITION)},TIMEOUT_TO_DO_PRETRANSFORM)};this.reset=
function(){r=!0;t()};this.getContentObject=function(){return w};this.getFlipDiv=function(){return v};this.getNextFlipper=function(){return K};this.getFadeout=function(){return r};this.getDepth=function(){return q};this.getBGDiv=function(){return f};this.setNextFlipper=function(a){K=a};this.setDepth=function(a,b){q=a;v.style.zIndex=Z_INDEX_ADD+a;w.style.zIndex=Z_INDEX_ADD+a+1;f.style.zIndex=Z_INDEX_ADD+a+3;s&&(s.style.zIndex=Z_INDEX_ADD+a);m&&(m.style.zIndex=Z_INDEX_ADD+a+4);!0!=b&&(G(v,q),G(w,q+2),
G(f,q+4),s&&B(s,l.nextShadow,q))};this.isFree=function(){return!I};this.clearContent=function(){w.contentCanvas.width=c;w.topCanvas.width=0;deleteAllChildren(w.vectorDiv)};var M;this.setBackgroundContent=function(a){M=a;deleteAllChildren(f);f.appendChild(M)};this.getBGCanvas=function(){M||(M=createFECanvas(a+"bgCont",c,b),f.appendChild(M));return M}}function createFECanvas(a,d,c){a=createCanvas(a);if(a.width!=d||a.height!=c)a.width=d,a.height=c;return a}
var createBackgroundDiv=function(a){a=createDiv(a);a.style.backgroundColor="#dddddf";return a},createShadowOnNextDiv=function(a,d){var c=createDiv(a);c.style.backgroundImage="-webkit-gradient(linear,"+(d?"right bottom,left bottom":"left bottom,right bottom")+", color-stop(1.00, rgba(0,0,0,0)),color-stop(0.00, rgba(0,0,0,0.6)) )";return c},createFoldShadow=function(a,d,c,b){a=createCanvas(a);a.width=d;a.height=c;var e=a.getContext("2d");b=b?e.createLinearGradient(d,0,0,0):e.createLinearGradient(0,
0,d,0);b.addColorStop(0,"rgba(0, 0, 0, 0)");b.addColorStop(0.72,"rgba(0, 0, 0, 0.2)");b.addColorStop(0.89,"rgba(0, 0, 0, 0.4)");b.addColorStop(1,"rgba(0, 0, 0, 0)");DEBUG_SHOW_FOLD_SHADOW?(e.lineWidth=16,e.strokeStyle="red",e.strokeRect(16,16,d-32,c-32)):(e.fillStyle=b,e.fillRect(0,0,d,c));return a},times=function(){return" "+((new Date).getTime()-startTime)+" "},sizeDim="px";
function sizeDiv(a,d,c,b){void 0==d&&void 0==c&&(d=window.innerWidth,c=window.innerHeight);a.style.width=b?d+"%":Math.ceil(d)+sizeDim;a.style.height=b?c+"%":Math.ceil(c)+sizeDim}function createDiv(a,d){var c=document.createElement("div");c.setAttribute("id",a);c.style.position="absolute";d&&(c.style.overflow="hidden");return c}function createCanvas(a,d,c){var b=document.createElement("canvas");b.setAttribute("id",a);b.style.position="absolute";void 0!=d&&void 0!=c&&sizeCanvas(b,d,c);return b}
function sizeCanvas(a,d,c){a.width=d;a.height=c}function setElementPosition(a,d){a.style.left=String(d.left).concat("px");a.style.top=String(d.top).concat("px")}function translate(a,d,c){a.style.webkitTransform="translate3d("+String(d)+sizeDim+",0px,"+String(c)+sizeDim+")"}function dev_scale(a,d,c){return prepare_xyz("scale",a,d,c)}function dev_translate(a,d,c){return prepare_xyz("translate",a,d,c)}function dev_translate_percents(a,d,c){return prepare_xyz("translate",a,d,c,"%")}
function dev_rotateXY(a){return"rotate("+a.toString()+"rad)"}function prepare_xyz(a,d,c,b,e){var z="scale"==a,n=z?1:0;e=z?"":e||sizeDim;void 0==d&&(d=n);void 0==c&&(c=n);void 0==b&&(b=n);return a+(DEV_3D?"3d("+d+e+","+c+e+","+b+e+")":"("+d+e+","+c+e+")")}var startTime;function centerRect(a,d,c,b){return{x:(a-c)/2,y:(d-b)/2}}function traceChildren(a){for(var d="",c=0;c<a.length;c++)d+=a[c].id+" ";console.log(d)}function deleteAllChildren(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
function parseVectorizedContentToDiv(a,d,c,b){b="undefined"!=typeof b?b:!0;for(var e=0;4>e;e++);d=d||createDiv();for(var e=[],z=0;z<a.length;z++){var n=a[z],p=0,L=n[p++].toString(),C=n[p++].toString(),B=parseFloat(n[p++]);parseFloat(n[p++]);var G=parseFloat(n[p++]),E=parseFloat(n[p++]),u=parseFloat(n[p++]),r=n[p++].toString(),n=parseFloat(n[p++]),F=Math.round(E*c),p=E=document.createElement("p");p.style.position="absolute";p.style.whiteSpace="nowrap";E.innerText=L;E.style.fontFamily=C;p.style.top=
px(Math.round(G*c));p.style.left=px(F);C=u;G=e[C];u="undefined"==typeof G?Math.floor(u*c):G.size;E.style.fontSize=px(u);E.style.color=r;d.appendChild(p);B*=c;if(b)for(;E.offsetWidth>B&&1<u;)u-=1,E.style.fontSize=px(u);if("undefined"==typeof G)e[C]={size:u,elements:[E]};else if(G.size>=u){if(G.size>u){e[C].size=u;for(var x in G.elements)r=G.elements[x],u=r.offsetWidth,r.style.fontSize=px(e[C].size),r.style.wordSpacing="0px",r.style.wordSpacing=px((u-r.offsetWidth)/(r.innerText.split(" ").length-1))}e[C].elements.push(E)}E.style.webkitTransform=
n?dev_rotateXY(n):"";E.style.webkitTransformOrigin=n?"0 0":"";L=L.split(" ");E.style.wordSpacing="0px";E.style.wordSpacing=px((B-E.offsetWidth)/(L.length-1))}return d}function px(a){return a.toString()+"px"}
function scaleAndPositionPageContent(a,d,c){var b=UP_SCALE*parseFloat(publicationData.getPageProperty(a,"width"));a=UP_SCALE*parseFloat(publicationData.getPageProperty(a,"height"));sizeDiv(d,b,a);void 0!=c&&(d.style.left=px(c.x),d.style.top=px(c.y),c=c.width/b,d.style.webkitTransform=dev_scale(c,c),d.style.webkitTransformOrigin="0 0")}
function getPageContentRect(a,d,c){var b=parseFloat(publicationData.getPageProperty(a,"proportions"));a={};a.width=Math.min(b*c,d);a.height=a.width/b;d=centerRect(d,c,a.width,a.height);a.x=d.x;a.y=d.y;return a}function applyRectToCanvas(a,d){a.width=d.width;a.height=d.height;a.style.left=px(d.x);a.style.top=px(d.y)}function fillCanvas(a,d,c){var b=a.getContext("2d");b.fillStyle=void 0!=d?d:"red";c?b.fillRect(c.x,c.y,c.width,c.height):b.fillRect(0,0,a.width,a.height)}
function getIsPreloader(){return!0==window.preloaderIsShown}function showPreloader(){window.preloaderIsShown||(window.preloaderIsShown=!0,workspace.preloader.add())}var hidePreloaderTimeout=null;function hidePreloader(){window.preloaderIsShown&&(workspace.preloader.del(),window.preloaderIsShown=!1)}function flipPage(a){a?pageMediator.right():pageMediator.left()}function getIsPortrait(){return innerHeight>innerWidth}function getIsAlbum(){return publicationData.type==ALBUM}
function ifParamExist(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");return null!=RegExp("[\\?&]"+a).exec(window.location.href)}window.debugSVG=""!=ifParamExist("s");window.debugSVG_IMG=""!=ifParamExist("i");window.debug_forceSaveScale=""!=ifParamExist("fs");var softFlip=!1;
function OnePage(a,d){function c(){var f;debugSVG||(F?(g.div.parentNode&&g.div.parentNode.removeChild(g.div),E()):deleteAllChildren(g.div));g.loaded?((f=document.getElementById("stubPage"))&&a.contains(f)&&a.removeChild(f),f=u().div(g.publishedSize).x,g.vector&&parseVectorizedContentToDiv(g.vector,g.div,f),debugSVG?(N.style.width=u().x+"px",N.style.height=u().y+"px",g.image.visibility="hidden"):(e("link",publicationData.page[y].links,g.div),e("video",publicationData.page[y].videos,g.div)),B()):z()&&
(f=document.getElementById("stubPage")||createDiv("stubPage"),sizeDiv(f,innerWidth,innerHeight),f.style.backgroundColor=publicationData.getPageProperty(y,"BGColor"),a.contains(f)||a.appendChild(f))}function b(a,f){y!=a&&(y&&z(y)&&!z(a)&&(g.image.style.visibility="visible"),y=a,fconsole.update("pos",y),x||showPreloader(),z()?(g.loaded=!1,k||(g.image.style.visibility="hidden"),g.size.set(publicationData.getPageProperty(y,"width"),publicationData.getPageProperty(y,"height")),d(!0),c(),hidePreloader(),
f&&f()):function(){g.vector=null;g.publishedSize=new Vector2(publicationData.getPageProperty(y,"width"),publicationData.getPageProperty(y,"height"));deleteAllChildren(g.div);loadManager.addPageToQueue({skipCurrentLoading:!0,image:g.image,quality:!0,position:y,onImageLoadComplete:function(){v=!0;g.loaded=!0;M=!1;k&&A.createPattern(g.image,"no-repeat");var a=new Vector2(g.image.naturalWidth,g.image.naturalHeight),f=g.size.x!=a.x||g.size.y!=a.y;g.size=a;d(f);debugSVG&&(N=document.createElement("object"),
N.setAttribute("type","image/svg+xml"),N.setAttribute("data","content/psout3.svg"),N.style.pointerEvents="none",g.div.appendChild(N),g.div.style.backgroundColor="white")},onPageLoadError:function(){g.loaded=!1},onAllIsComplete:function(a,b){g.vector=b;c();hidePreloader();f&&f()},onJSLoadComplete:function(){}})}())}function e(f,b,c,d){var e=u().div(g.publishedSize).x;if("undefined"!=typeof b&&b){var s;for(s=0;s<b.length;s++){var m=b[s],h=new Vector2(m.x,m.y),J=new Vector2(m.width,m.height),H=createDiv(f+
s);(function(a,f,b,c){a.style.webkitTransformOrigin="0 0";var d=c?Math.sin(c):0;c=c?Math.cos(c):1;a.style.webkitTransform="matrix("+[c,d,-d,c,f.x,f.y].join()+")";sizeDiv(a,b.x,b.y,!1)})(H,h.mul(e),J.mul(e),m.angle);"undefined"!=typeof m.zindex&&(H.style.zIndex=m.zindex);if("highlight"==f)H.style.backgroundColor=d||highlight.getFillStyle(),c.appendChild(H);else if("link"==f)H.style.backgroundColor=publicationData.linkcolor,H.style.opacity="0.23",(h=m.urls)&&0!=h.length?(m=document.createElement("a"),
m.href=h[0],m.target="_blank",m.appendChild(H),c.appendChild(m)):void 0!=m.page&&(function(a){setClickEvents(H,"md",!1);H.addEventListener(SINGLE_CLICK,function(){pageMediator.goToPage(parseInt(a))})}(m.page),c.appendChild(H));else if("video"==f){H.id="video."+m.id;if(m.showImage){var y=video.getVideoImageUrl(m.imageUri);(function(a){changeUrlWhenPubl(y,function(f){a.style.backgroundImage="url('"+f+"')";a.style.backgroundSize="100% 100%"})})(H)}h=new Image;J=m.height*e;J=50<J?50:0.8*J;h.src=video.getPlayImage();
H.appendChild(h);h.style.position="absolute";h.style.margin="auto";h.style.left="0";h.style.right="0";h.style.top="0";h.style.bottom="0";h.style.height=px(J);(function(f){setClickEvents(H,"md",!1);H.addEventListener(SINGLE_CLICK,function(){video.play(f.type,f.id,function(){a.style.visibility="visible"});a.style.visibility="hidden"})})(m);c.appendChild(H)}}}}function z(a){a=void 0!=a?a:y;return publicationData.getPageProperty(a,"stub")}function n(){var a=y+(t.right?1:-1);t.loaded=!1;t.image=new Image;
K&&I.appendChild(t.image);loadManager.addPageToQueue({skipCurrentLoading:!1,image:t.image,quality:!0,position:a,onImageLoadComplete:function(){t.loaded=!0;if(K){var a=new Vector2(t.image.naturalWidth,t.image.naturalHeight),f=u().x,a=(new Vector2(innerWidth,innerHeight)).stretchToMe(a.x/a.y,!0);t.image.style.width=a.x+"px";t.image.style.height=a.y+"px";C(t.image,t.right?f:-a.x,0,!1)}}})}function p(){function a(f,d,e){var s=Math.round(d.x);d=Math.round(d.y);var J=0<s?0:Math.abs(s/e),m=0<d?0:Math.abs(d/
e),J=Math.min(f.width*e,b)/e-J,m=Math.min(f.height*e,c)/e-m;(J||m)&&A.drawImage(f,s,d,f.width*e,f.height*e)}if(g.loaded||z()){var b=q.width,c=q.height;if(!M&&!t.offset&&(t.changed||v||f||s||m)){A.clearRect(0,0,b,c);if(z())A.fillStyle=publicationData.getPageProperty(y,"BGColor"),A.fillRect(0,0,b,c);else{a(g.image,w,D);var d=Math.round(w.x),e=Math.round(w.y);C(g.div,d,e,!1)}m=s=f=v=!1;t.changed=!1}if(t.offset&&t.changed){var k,l,e=t.offset,d=innerWidth;t.right?(d=0+(d-e),e/=2,k=d+e,l=e):(k=0,l=e/2,
d=k+l,e=l);A.clearRect(0,0,b,c);a(g.image,w,D);if(t.loaded){var h=t.image;if(debug_forceSaveScale)H=t.right?k/D:0,u=0,p=l/D,J=c/D;else var J=(new Vector2(b,c)).stretchToMe(h.width/h.height,!1),H=k*h.width/J.x,u=0,p=l*h.width/J.x,J=c*h.width/J.x;A.drawImage(h,H,u,p,J,k,0,l,q.height)}else A.fillStyle="#efefef",A.fillRect(k,0,l,q.height);l=k=0;t.right?l=e:k=e;k=A.createLinearGradient(d+k,0,d+l,0);k.addColorStop(0,"rgba(0, 0, 0, 0)");k.addColorStop(0.72,"rgba(0, 0, 0, 0.2)");k.addColorStop(0.89,"rgba(0, 0, 0, 0.4)");
k.addColorStop(1,"rgba(0, 0, 0, 0)");A.fillStyle="#dddddf";A.fillRect(d,0,e,q.height);A.fillStyle=k;A.fillRect(d,0,e,q.height);t.changed=!1}}}function L(){var a=u();if(s||v||m)g.image.style.width=1!=D?px(a.x):null,g.image.style.height=1!=D?px(a.y):null,a=g.size.map(function(a){return Math.floor((a-1)*D-1)}),sizeDiv(I,a.x,a.y),sizeDiv(g.div,a.x,a.y),v=s=!1;if(f||m){var a=Math.round(w.x),b=Math.round(w.y);C(I,a,b,!1);m=f=!1}}function C(a,f,b,c){c=c?"%":"px";a.style.left=f.toString()+c;a.style.top=b.toString()+
c}function B(){search.active&&search.pages[y]?highlight.getHighlights(y,function(a){G();g.div.appendChild(O);e("highlight",a,O)}):G()}function G(){deleteAllChildren(O);g.div.contains(O)&&g.div.removeChild(O)}function E(){g.div=createDiv("contentDiv");k?a.appendChild(g.div):(g.div.style.webkitTransform=null,I.appendChild(g.div))}function u(a){a=a||D;return g.size.map(function(f){return Math.floor(f*a)})}var r=window.system.platform.version,F="safari"==window.system.browser.name&&fbUtils.isArray(r)&&
2<=r.length&&"4"==r[0]&&2<=r[1],x="safari"==window.system.browser.name&&fbUtils.isArray(r)&&3==r.length&&"4"==r[0]&&"0"==r[1]&&"4"==r[2],l=ifParamExist("c")?"canvas":"webkit",k="canvas"==l,K="webkit"==l;if(K)var I=createDiv("scrollDiv");var g={};g.bufferImage=new Image;var q=document.createElement("canvas"),A=q.getContext("2d");g.loaded=!1;var v,w=new Vector2(0,0),D=0.1,f,s,m,y;g.size=new Vector2;g.publishedSize=new Vector2(100,100);this.goToPage=function(a){b(a,function(){customEvents.fireEvent(ANDROID_PAGE_PREPARED,
{page:z()?[]:[y]})})};this.resize=function(){c();k?(q.width=innerWidth,q.height=innerHeight):sizeDiv(a,innerWidth,innerHeight)};this.setOffset=function(a,b){w.set(a);b&&K||(f=!0)};var t={};this.setFlipOffset=function(a,f){!t.offset&&a&&n();t.offset=a;t.right=f;t.changed=!0};this.setScale=function(a,f){D=a;f&&K||(s=!0)};this.startPinchMode=function(){g.div.style.visibility="hidden";debugSVG||k||(this.pinchRedrawInterval=setInterval(function(){m=!0},1E3))};this.stopPinchMode=function(){c();this.pinchRedrawInterval&&
(clearInterval(this.pinchRedrawInterval),this.pinchRedrawInterval=null);g.div.style.visibility="visible";K&&(s=f=!0)};this.updateTopContent=function(){c()};var N,M=!1;this.setFinished=function(){M=!0;K&&a.removeChild(t.image)};var O=createDiv("highlightContainer");this.setHighlight=function(a){a?B():(search.active=!1,G())};this.set=function(f,c){fconsole.update("mode",l);k?(a.style.overflow="visible",a.appendChild(q)):(a.style.position="absolute",I.style.webkitTransform=null,a.style.webkitTransform=
null,a.style.overflow="hidden",a.appendChild(I));g.image=new Image;k||(g.image.style.webkitTransform=null,g.image.style.position="absolute",I.appendChild(g.image),g.image.style.border="1px solid #333333");E();b(f,c)};this.getScaledSize=u;this.getImageLoaded=function(){return g.loaded};this.isStub=function(){return z()};this.getContentSize=function(){return g.size};this.drawFrame=k?p:L;this.canFlip=function(a){return a?y<getBookLength():1<y}}
function SimpleViewer(a){function d(){(new Date).getTime();window.requestAnimFrame=window.requestAnimFrame||function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();(function s(){k.drawFrame(D);requestAnimFrame(s)})()}function c(a,b){a!=x&&(x=a,fconsole.update("scale",x),k.setScale(x,b),b||B())}function b(a,b){a.sub(F).vlength()&&(F=
a,k.setOffset(F,b))}function e(a,b){var c=new z(b);return a.clip(c.xmin,c.ymin,c.xmax,c.ymax)}function z(a){var b=k.getScaledSize(a).x;a=k.getScaledSize(a).y;var c=a>innerHeight;b>innerWidth?(this.xmax=0,this.xmin=innerWidth-b):this.xmax=this.xmin=innerWidth/2-b/2;c?(this.ymax=0,this.ymin=innerHeight-a):this.ymax=this.ymin=innerHeight/2-a/2}function n(a,d,m){var g=x;a=d&&C(l.map,x)>=l.map.length-1?l.defaultPos:C(l.map,x*(d?2:1))+(d?0:a?1:-1);a=Math.min(Math.max(a,0),l.map.length-1);a=l.map[a];m=m?
m:u?new Vector2(innerWidth/2,innerHeight/2):new Vector2(publicationData.rtlMode?innerWidth:0,0);g=F.sub(m.sub(F).mul(a/g-1));g=e(g,a);c(a);b(g);k.updateTopContent()}function p(a,d){var m,g=k.getContentSize();m="change"==a;var t="resize"==a,w=m&&!d&&r,p=l,q=m&&d||t;if(q){var n=(new Vector2(innerWidth,innerHeight)).stretchToMe(g.x/g.y,!0).x/g.x,p=innerWidth/g.x,g=p/0.8,v;u?(n=[n],v=1.5):(n=[p],v=Math.sqrt(g/p),n=n.concat([p*v,g]));for(;2.15>n[n.length-1]*v;)n[n.length]=n[n.length-1]*v;L(n,0.25,v);L(n,
0.5,v);L(n,0.75,v);L(n,1,v);p={defaultPos:0,map:n,textVisibleMaxPos:4}}fconsole.log(m,d,t,q||u||!window.debug_forceSaveScale&&C(l.map,x)>l.textVisibleMaxPos);t=q||u||!window.debug_forceSaveScale&&C(l.map,x)>l.textVisibleMaxPos?p.map[p.defaultPos]:x;q=k.getScaledSize(t).x;g=k.getScaledSize(t).y;n=F.vclone();w||(n.x=u?(innerWidth-q)/2:publicationData.rtlMode?innerWidth-q:0);m&&(n.y=u?(innerHeight-g)/2:0);m=e(n,t);l=p;b(m);c(t)}function L(a,b,c){for(var d=Math.abs(a[0]-b),e=1,g=0;e<a.length;){var k=
Math.abs(a[e]-b);k<d&&(d=k,g=e);e++}(b+d)/(b-d)<c&&0!=g&&(a[g]=b)}function C(a,b){for(var c=0;c<a.length;c++){var d=a[c];if(0==c){if(b<=d||1==a.length)return 0}else{if(c==a.length-1)return a.length-1;if(b<a[c])return b<=(a[c-1]+a[c])/2?c-1:c;if(b<=(a[c]+a[c+1])/2)return c}}throw"determineScale abnormal return";}function B(){customEvents.fireEvent(ZOOM_LEVEL_CHANGED_FOR_WORKSPACE,{isSmallest:0==C(l.map,x),isLargest:C(l.map,x)==l.map.length-1})}function G(a,c,d){function g(a){I.active=!1;a.ctrlKey&&
(c.sendPinch&&(c.startPinch&&c.startPinch(new Vector2(a.pageX,a.pageY)),c.sendPinch(z,new Vector2(0,0),new Vector2(a.pageX,a.pageY)),c.endPinch&&c.endPinch()),a.stopImmediatePropagation());a.altKey&&c.sendPinch&&(c.startPinch&&c.startPinch(new Vector2(a.pageX,a.pageY)),c.sendPinch(A,new Vector2(0,0),new Vector2(a.pageX,a.pageY)),c.endPinch&&c.endPinch());a.shiftKey&&c.handleDoubleClick(a);var b=a.currentTarget;if(Modernizr.touch){if(1<a.touches.length){l(a);return}b.addEventListener(DOWN_EVENT,l,
!1)}b.removeEventListener(DOWN_EVENT,g,!1);b.addEventListener(MOVE_EVENT,n,!1);b.addEventListener(UP_EVENT,r,!1);b.addEventListener("touchcancel",r,!1);b.addEventListener("mouseout",r,!1);a=a.touches?a.touches[0]:a;b.pos=new Vector2(a.pageX,a.pageY);D.disabledThisTime=!1;x()}function n(a){a.preventDefault();var c=a.touches?a.touches[0]:a,c=new Vector2(c.pageX,c.pageY),f=a.currentTarget.pos;a.currentTarget.pos=c;a=c.sub(f);h.dv0x=h.dv0x||a.x;if(h.timeStamp){c=(new Date).getTime();f=c-h.timeStamp;h.vDiff=
h.vDiff.add(a);h.moveTime+=f;h.timeStamp=c;h.trackLength+=Math.abs(a.x);h.movePath.push({dv:a,time:f});c=k.getScaledSize(void 0).x<=innerWidth||k.isStub();d&&(f=h.vDiff.y?Math.abs(h.vDiff.x)/Math.abs(h.vDiff.y):1E10,Math.abs(h.vDiff.x)>B/1.5*(1.5-f)?h.horizontalAllowed=!0:!h.vDiff.y||1.5<f||h.horizontalAllowed||(a.x=0));if(1E3<h.moveTime||h.dv0x&&a.x&&h.dv0x/Math.abs(h.dv0x)!=a.x/Math.abs(a.x))h.slideDisabledThisTime=!0;!h.slideDisabledThisTime&&h.vDiff.x&&0.5>Math.abs(h.vDiff.y)/Math.abs(h.vDiff.x)&&
(a.y=0);if(c=c&&!h.slideDisabledThisTime&&4<h.trackLength&&75<h.moveTime){for(var g=h.movePath,c=k.getScaledSize(void 0).y>innerHeight,s,l,p,q=p=l=f=s=0;q<g.length;q++){var r=g[q];s+=r.dv.x;f+=r.dv.y;l+=Math.abs(r.dv.x);p+=r.time}g=Math.abs(s);l=Math.abs(l-g);s=0>s;14>l&&7<g&&(!c&&1>=Math.abs(f)/g||c&&g>7+200*Math.abs(f)/g&&g>0.2*p)?(flipPage(s),c=!0):c=!1}c&&(h.slideDisabledThisTime=!0)}if(a.x||a.y)b(e(F.add(a))),0!=v&&(w={dv:a,time:(new Date).getTime()-v}),v=(new Date).getTime()}function l(a){if(1<
a.touches.length){var b=a.currentTarget,f=a.touches[0];a=a.touches[1];b.pos=new Vector2((f.pageX+a.pageX)/2,(f.pageY+a.pageY)/2);b.startDist=E(f,a);b.removeEventListener(UP_EVENT,r,!1);b.removeEventListener("touchcancel",r,!1);b.removeEventListener(MOVE_EVENT,n,!1);b.removeEventListener(DOWN_EVENT,l,!1);b.addEventListener(MOVE_EVENT,p,!1);b.addEventListener(UP_EVENT,q,!1);b.addEventListener("touchcancel",q,!1);c.startPinch&&c.startPinch(b.pos)}}function p(a){a.preventDefault();if(1<a.touches.length){var b=
a.currentTarget,f=a.touches[0],d=a.touches[1];a=E(f,d);var f=new Vector2((f.pageX+d.pageX)/2,(f.pageY+d.pageY)/2),d=a/b.startDist,e=f.sub(b.pos);c.sendPinch(d,e,f);b.startDist=a;b.pos=f}}function q(a){var b=a.currentTarget,f=a.touches.length;if(0<f){b.removeEventListener(MOVE_EVENT,p,!1);b.removeEventListener(UP_EVENT,q,!1);b.removeEventListener("touchcancel",q,!1);b.addEventListener(MOVE_EVENT,n,!1);b.addEventListener(UP_EVENT,r,!1);b.addEventListener("touchcancel",r,!1);var d=a.touches?a.touches[0]:
a;b.pos=new Vector2(d.pageX,d.pageY);x()}c.endPinch&&c.endPinch();0==f&&r(a)}function u(a){h.timeoutID||(h.timeoutID=setTimeout(function(){h.horizontalAllowed=!1;h.timeoutID=null},a))}function r(a){var b=a.currentTarget;Modernizr.touch&&a.touches&&0!=a.touches.length||(b.removeEventListener(MOVE_EVENT,n,!1),b.removeEventListener(UP_EVENT,r,!1),b.removeEventListener("touchcancel",r,!1),b.removeEventListener("mouseout",r,!1),b.addEventListener(DOWN_EVENT,g,!1));h.xDiff=0;h.yDiff=0;u(C);D.active?D.finishing||
D.stop():(w&&100>(new Date).getTime()-v&&(w.dv.x&&k.getScaledSize(void 0).x>innerWidth||w.dv.y&&k.getScaledSize(void 0).y>innerHeight)&&I.startKinematics(w.dv,w.time),w=null,v=0)}function x(){h.timeStamp=(new Date).getTime();h.moveTime=0;h.movePath=[];h.trackLength=0;h.slideDisabledThisTime=!1;h.dv0x=0;h.vDiff.set(0,0)}var z=1.15,A=0.8,B=innerWidth/4,C=1250;a.addEventListener(DOWN_EVENT,g,!1);var h={};h.vDiff=new Vector2(0,0)}function E(a,b){var c=a.pageX-b.pageX,d=a.pageY-b.pageY;return Math.sqrt(c*
c+d*d)}var u=publicationData.type==PT_PHOTOALBUM,r=publicationData.type==PT_BOOK,F=new Vector2(0,0),x=0.1,l,k=new OnePage(a,function(a){p("change",a)});this.goToPage=function(a){k.goToPage(a)};var K=this;setInterval(function(){K.width==innerWidth&&K.height==innerHeight||K.resize()},1E3);this.resize=function(){this.width=innerWidth;this.height=innerHeight;k.getImageLoaded()&&p("resize");k.resize()};var I={startKinematics:function(a,b){},active:!1,iterate:function(a){this.time+=a;this.time=Math.min(this.time,
this.duration);a=this.time/this.duration-1;this.time==this.duration&&(this.active=!1);return I.startPoint.add(I.endPoint.sub(I.startPoint).mul(a*a*a+1))}},g,q=function(){var a=document.createElement("p");a.style.opacity="0.7";a.style.backgroundColor="#e0efee";a.style.color="#11111f";a.style.fontSize="18px";a.style.zIndex=1E3;a.style.position="absolute";this.element=a};q.prototype.setText=function(a){this.element.innerText=a};q.prototype.positionMe=function(a){this.element.style.left=px(a.x-this.element.offsetWidth/
2);this.element.style.top=px(a.y-this.element.offsetHeight/2)};var A=new q;this.sendMove=function(a){};var v=0,w;this.stopDrag=function(){};this.startPinch=function(b){I.active=!1;a.appendChild(A.element);A.positionMe(b);g?(clearTimeout(g),g=null):k.startPinchMode()};this.endPinch=function(){a.removeChild(A.element);g=setTimeout(function(){k.stopPinchMode();g=null;B()},k.isStub()||debugSVG?0:500)};this.sendPinch=function(a,d,g){x*a<l.map[0]?a=l.map[0]/x:x*a>l.map[l.map.length-1]&&(a=l.map[l.map.length-
1]/x);d=d.add(g.sub(F).mul(1-a));d=F.add(d);a*=x;d=e(d,a);c(a,!0);b(d,!0);A.setText(window.LOCALS.ZOOM+" "+(100*x).toFixed(0)+"%");A.positionMe(g)};this.incZoom=function(){n(!0)};this.decZoom=function(){n(!1)};this.setHighlight=function(a){k.setHighlight(a)};this.set=function(b,c){setElementPosition(a,{left:0,top:0});k.set(b,c);this.resize();d();G(a,this,publicationData.type!=PT_PHOTOALBUM)};this.clear=function(){};this.handleDoubleClick=function(a){a=a.touches?a.touches[0]:a;a=new Vector2(a.pageX,
a.pageY);n(!0,!0,a)};var D={active:!1,handleFlipFinished:function(){k.setFinished();flipPage(this.right)},start:function(a,b){this.drag=0;this.userDrag=a;this.right=b;this.active=!0;this.setChanged()},stop:function(){this.active=this.finishing=!1;this.setChanged()},updateDrag:function(a){this.userDrag=a},setChanged:function(){this.changed=!0;k.setFlipOffset(this.active?this.drag:0,this.right)},iterate:function(a){this.finishing?(this.drag+=(2*innerWidth-this.drag)/2,1>Math.abs(this.drag-2*innerWidth)&&
(this.handleFlipFinished(),this.stop())):this.drag+=(this.userDrag-this.drag)/5;this.setChanged()},finish:function(){this.finishing=!0;this.setChanged()}}};
