// Created 9/26/2013 8:30:00 PM
function IOSBook(s,c){this.type=c||orientationObserver.getType();s=s||1;this.onePage=new OnePagePublication(s);this.twoPage=new TwoPagePublication(s);this.zoomBook=new ZoomIOSPublication(1);this.onePage.initSizes();this.twoPage.initSizes();this.touchTrigg=0;1==this.type?this.onePage.drawBook():2==this.type?this.twoPage.drawBook():3==this.type&&(this.zoomBook.initSizes(3.3),this.zoomBook.drawBook());this.goToPage=function(a){1==this.type?this.onePage.goToPage(a):2==this.type?this.twoPage.goToPage(a):
3==this.type&&this.zoomBook.goToPage(a)};var d=this,n=function(a){1==d.type&&d.onePage.goToZoom(a);if(2==d.type){var b=a.target.id.match(/\d+/i);d.twoPage.goToZoom(b)}3==d.type&&(2===orientationObserver.getType()?d.zoomBook.goToTwoPage(a):d.zoomBook.goToOnePage(a))};el.id("mainFrame").addEventListener("dblclick",n);el.id("mainFrame").addEventListener("touchend",function(){0===d.touchTrigg?(d.touchTrigg++,setTimeout(function(){d.touchTrigg=0},250)):d.twoPage.gesture||d.onePage.gesture||d.zoomBook.gesture||
n(event)});customEvents.addListener(ROTATE_DEVICE,function(a){2===a.data&&1===d.type?(d.type=2,d.onePage.destroyBook(),setTimeout(function(){d.twoPage.initSizes();var a=pageTable.getUserIDFromFileID(pageMediator.page);d.twoPage.drawBook(a)},10)):1===a.data&&1===d.type?(d.type=1,d.onePage.destroyBook(),setTimeout(function(){d.onePage.initSizes();d.onePage.drawBook(pageMediator.page)},10)):1===a.data&&2===d.type?(d.type=1,d.twoPage.destroyBook(),setTimeout(function(){d.onePage.initSizes();d.onePage.drawBook(pageMediator.page)},
10)):2===a.data&&2===d.type&&(d.type=2,d.twoPage.destroyBook(),setTimeout(function(){d.twoPage.initSizes();d.twoPage.drawBook(pageMediator.page)},10))});customEvents.addListener(ZOOM_ANIMATION_START,function(){});customEvents.addListener(ZOOM_ANIMATION_END,function(a){d.type=3;customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:3});d.zoomBook.initSizes(a.data.zoomFactor,a.data.page);d.zoomBook.drawBook(a.data.page);if(GAEnable){var b=window.location.pathname.split("/");_trackEvent(b[b.length-4]+"","Zooming",
"page"+a.data.page)}});customEvents.addListener(ZOOM_ANIMATION_END_TO_ONE,function(a){d.type=1;customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:1});d.onePage.initSizes();d.onePage.drawBook(a.data.page);if(GAEnable){var b=window.location.pathname.split("/");_trackEvent(b[b.length-4]+"","Zooming out","page"+a.data.page)}});customEvents.addListener(ZOOM_ANIMATION_END_TO_TWO,function(a){customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:2});d.type=2;d.twoPage.initSizes();d.twoPage.drawBook(a.data.page);if(GAEnable){var b=
window.location.pathname.split("/");_trackEvent(b[b.length-4]+"","Zooming out","page"+a.data.page)}});customEvents.addListener(ZOOM_ZOOM_ANIMATION_END,function(a){customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:3});d.type=3;d.zoomBook.initSizes(a.data.zoomFactor,a.data.page);d.zoomBook.drawBook(a.data.page,a.data.startPos)});el.id("mainFrame").addEventListener("gesturestart",function(){ZOOM_LOCK||(1===d.type?d.onePage.gesturestart(event):2===d.type?d.twoPage.gesture||d.twoPage.gesturestart(event):3===
d.type&&d.zoomBook.gesturestart(event))},!0);el.id("mainFrame").addEventListener("gesturechange",function(){ZOOM_LOCK||(1===d.type?d.onePage.gesturechange(event):2===d.type?d.twoPage.gesturechange(event):3===d.type&&d.zoomBook.gesturechange(event))},!0);el.id("mainFrame").addEventListener("gestureend",function(){ZOOM_LOCK||(1===d.type?d.onePage.gestureend(event):2===d.type?d.twoPage.gestureend(event):3===d.type&&d.zoomBook.gestureend(event))},!0);customEvents.addListener(START_ZOOM_PRELOADER,function(a){ZOOM_LOCK=
!0;a=void 0!=a.data?a.data.shift:0;var b=el.add("div");b.id="preloaderZOOM";b.style.position="absolute";b.style.left=window.innerWidth/2+a+"px";b.style.top=window.innerHeight/2+"px";b.style.width="10em";b.style.height="10em";b.style.margin="-3em 0 0 -5em";b.style.zIndex=1E7;b.style.webkitTransform="translateZ(150px)";workspace.preloader.add(b);el.id("mainFrame").appendChild(b);page=null});customEvents.addListener(STOP_ZOOM_PRELOADER,function(){el.del("preloaderZOOM");setTimeout(function(){ZOOM_LOCK=
!1},300)});var a=function(){1===d.type?d.onePage.touch(event):2===d.type?d.twoPage.touch(event):3===d.type&&d.zoomBook.touch(event);system.device.iphone&&window.scrollTo(0,1)},b=function(){1===d.type?d.onePage.endmove(event):2===d.type?d.twoPage.endmove(event):3===d.type&&d.zoomBook.endmove(event)};Modernizr.touch?(el.id("mainFrame").addEventListener("touchstart",a,!0),el.id("mainFrame").addEventListener("touchend",b,!0)):(el.id("mainFrame").addEventListener("mousedown",a,!0),el.id("mainFrame").addEventListener("mouseup",
b,!0))}iosContent={};
function OnePagePublication(s){this.HORIZONTAL_MARGIN=this.VERTICAL_MARGIN=10;this.bookLeft=this.bookTop=this.bookHeight=this.bookWidth=this.pageHeight=this.pageWidth=0;this.active=this.block=!1;this.currentPage=s||1;this.pageBuff=1;this.flipSpeed=500;this.gesture=!1;this.loadBuffers={};this.initSizes=function(){var a=publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>a?(this.bookHeight=window.innerHeight-2*this.VERTICAL_MARGIN,this.bookWidth=this.bookHeight*
a,this.bookLeft=(window.innerWidth-this.bookWidth)/2,this.bookTop=this.VERTICAL_MARGIN):(this.bookWidth=window.innerWidth-2*this.HORIZONTAL_MARGIN,this.bookHeight=this.bookWidth/a,this.bookLeft=this.HORIZONTAL_MARGIN,this.bookTop=(window.innerHeight-this.bookHeight)/2);this.pageHeight=this.bookHeight;this.pageWidth=this.bookWidth;this.translateX=2*this.bookLeft+this.pageWidth};this.init=function(){var a=this;customEvents.addListener(SHOW_SEARCH_RESULTS,function(){if(a.active){highlight.show(a.currentPage);
for(var b=a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.show(b)}});customEvents.addListener(CANCEL_SEARCH,function(){if(a.active){highlight.hide(a.currentPage);for(var b=a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.hide(b)}});customEvents.addListener(BOOK_FLIPPING_START,function(){a.block=!0});customEvents.addListener(BOOK_FLIPPING_END,function(){a.block=!1});customEvents.addListener(IOS_LOAD_PAGE_START,function(a){var e=
a.data.page;1!==a.data.type||publicationData.page[e].stub||(a=el.add("div"),a.id="preloader"+e,a.style.position="absolute",a.style.left="50%",a.style.top="50%",a.style.width="10em",a.style.height="10em",a.style.margin="-3em 0 0 -5em",workspace.preloader.add(a),publicationData.page[e].wide?el.id("widePage"+e).appendChild(a):el.id("divPage"+e).appendChild(a))});customEvents.addListener(IOS_LOAD_BITMAP_END,function(a){var e=a.data.page;1!==a.data.type||publicationData.page[e].stub||el.del("preloader"+
e)});customEvents.addListener(IOS_LOAD_VECTOR_END,function(a){})};this.drawBook=function(a){this.active=!0;a=a||-10;-10!=a&&(this.currentPage=a);this.init();el.id("publicationDiv")?el.id("publicationDiv"):(a=el.add("div"),a.id="publicationDiv",a.style.width=this.bookWidth+"px",a.style.height=this.bookHeight+"px",a.style.top=this.bookTop+"px",a.style.left=this.bookLeft+"px",a.style.position="absolute",a.style.textAlign="center",a.style.opacity="1",el.id("mainFrame").appendChild(a));this.drawPage(this.currentPage);
for(a=this.currentPage-this.pageBuff;a<=1*this.currentPage+this.pageBuff;a++)a!==this.currentPage&&this.drawPage(a)};this.drawPage=function(a){if(publicationData.page[a]&&!el.id("divPage"+a)){var b=publicationData.page[a].wide;if(b){var e=el.add("div");e.id="divPage"+a;e.className="oneBook";e.style.width=this.pageWidth+"px";e.style.height=this.pageHeight+"px";e.style.position="absolute";e.style.backgroundColor="rgba(0,0,0,0)";e.style.color="black";e.style.left=publicationData.rtlMode?a>this.currentPage?
-window.innerWidth+"px":a<this.currentPage?window.innerWidth+"px":"":a<this.currentPage?-window.innerWidth+"px":a>this.currentPage?window.innerWidth+"px":"";var c=publicationData.rtlMode?publicationData.pageCount+a:publicationData.pageCount-a;e.style.zIndex=c+"";c=null;el.id("publicationDiv").appendChild(e)}var f=el.add("div");f.id=b?"widePage"+a:"divPage"+a;f.className="oneBook";f.style.width=this.pageWidth+"px";f.style.height=b?this.pageHeight/2+"px":this.pageHeight+"px";f.style.position="absolute";
"photo_album"==publicationData.type||"document"==publicationData.type?f.style.backgroundColor="rgba(0,0,0,0)":(f.style.backgroundColor=publicationData.page[a].BGColor||publicationData.page.defaults.BGColor,HTML5lib.boxShadow(f,"0px 0px 3px #000"));f.style.color="black";b&&(f.style.top=this.pageHeight/4+"px");publicationData.rtlMode?!b&&a>this.currentPage?f.style.left=-window.innerWidth+"px":!b&&a<this.currentPage?f.style.left=window.innerWidth+"px":b||(f.style.left=""):!b&&a<this.currentPage?f.style.left=
-window.innerWidth+"px":!b&&a>this.currentPage?f.style.left=window.innerWidth+"px":b||(f.style.left="");c=publicationData.rtlMode?publicationData.pageCount+a:publicationData.pageCount-a;f.style.zIndex=c+"";c=null;c=this.injectCanvas(f,a);b?e.appendChild(f):el.id("publicationDiv").appendChild(f);publicationData.page[a].stub?(customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:a,type:1}),customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:a,type:1}),ZOOM_LOCK&&el.id("exPage"+a)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),
setTimeout(function(){el.del("exPage"+a)},50))):(customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:a,type:1}),this.loadImage(c,a))}};this.injectCanvas=function(a,b){var e=publicationData.page[b].wide?this.pageHeight/2:this.pageHeight,c=publicationData.page[b].width||publicationData.page.defaults.width,f=publicationData.page[b].height||publicationData.page.defaults.height,h=c/f;if(this.pageWidth/e>h)var g=e,d=g*h,h=(this.pageWidth-d)/2,e=0;else d=this.pageWidth,g=d/h,h=0,e=(e-g)/2;var l=el.add("canvas");
l.id="substraitCanvas"+b;l.width=d;l.height=g;l.style.position="absolute";l.style.left=h+"px";l.style.top=e+"px";a.appendChild(l);var k=d/(2*c);"photo_album"!=publicationData.type&&"document"!=publicationData.type||HTML5lib.boxShadow(l,"0px 0px 3px #000");var m=publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===m||"js+png"===m)m=el.add("div"),m.id="contentDiv"+b,m.style.width=2*c+"px",m.style.height=2*f+"px",m.style.position="absolute",m.style.left=h+"px",m.style.top=
e+"px",m.style.webkitTransformOrigin="0% 0%",m.style.webkitTransform="scale("+k+")",a.appendChild(m);var q=el.add("canvas");q.id="highlightCanvas"+b;q.width=d;q.height=g;q.style.position="absolute";q.style.left=h+"px";q.style.top=e+"px";q.style.opacity=0;a.appendChild(q);new LinksLayer(q,b);highlight.show(b,q);var r=function(){q.style.opacity=1;customEvents.removeListener(IOS_LOAD_BITMAP_END,r)};customEvents.addListener(IOS_LOAD_BITMAP_END,r);return l};this.destroyPage=function(a){el.id("divPage"+
a)&&el.del("divPage"+a)};this.destroyBook=function(){el.del("publicationDiv");this.active=!1};this.goToPage=function(a){var b=this;if(a==this.currentPage+1)a=this.currentPage-this.pageBuff,b.destroyPage(a),publicationData.rtlMode?this.shiftRight():this.shiftLeft(),this.currentPage++,this.drawPage(this.currentPage+this.pageBuff);else if(a==this.currentPage-1)a=this.currentPage+this.pageBuff,b.destroyPage(a),publicationData.rtlMode?this.shiftLeft():this.shiftRight(),this.currentPage--,this.drawPage(this.currentPage-
this.pageBuff);else if(a!=this.currentPage){if(1*a>1*this.currentPage){var e=1*this.currentPage+1;this.clearContent(e);publicationData.rtlMode?this.shiftRight():this.shiftLeft()}else e=this.currentPage-1,this.clearContent(e),publicationData.rtlMode?this.shiftLeft():this.shiftRight();this.currentPage=a;var c=function(){b.destroyBook();b.drawBook(b.currentPage);delete c};window.setTimeout(c,b.flipSpeed);pageMediator.changePage(a)}};this.clearContent=function(a){el.id("divPage"+a)&&(el.id("divPage"+
a).style.backgroundColor="white",el.id("substraitCanvas"+a)&&el.del("substraitCanvas"+a),el.id("videoDiv"+a)&&el.del("videoDiv"+a),el.id("contentDiv"+a)&&el.del("contentDiv"+a),el.id("highlightCanvas"+a)&&el.del("highlightCanvas"+a))};this.shiftLeft=function(){for(var a=this.currentPage-this.pageBuff;a<=this.currentPage+this.pageBuff;a++)if(el.id("divPage"+a)){var b=el.id("divPage"+a);HTML5lib.duration(b,this.flipSpeed);0==1*HTML5lib.getParseTranslate(b).x?(customEvents.fireEvent(BOOK_FLIPPING_START),
HTML5lib.translate(b,-this.translateX,0,0)):1*HTML5lib.getParseTranslate(b).x==-this.translateX?HTML5lib.translate(b,2*-this.translateX,0,0):1*HTML5lib.getParseTranslate(b).x==2*this.translateX?(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,this.translateX,0,0)):(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,0,0,0))}var e=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:e.currentPage})},this.flipSpeed)};this.shiftRight=function(){for(var a=
this.currentPage-this.pageBuff;a<=this.currentPage+this.pageBuff;a++)if(el.id("divPage"+a)){var b=el.id("divPage"+a);HTML5lib.duration(b,this.flipSpeed);0==1*HTML5lib.getParseTranslate(b).x?(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,this.translateX,0,0)):1*HTML5lib.getParseTranslate(b).x==this.translateX?(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,2*this.translateX,0,0)):1*HTML5lib.getParseTranslate(b).x==2*-this.translateX?(customEvents.fireEvent(BOOK_FLIPPING_START),
HTML5lib.translate(b,-this.translateX,0,0)):(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,0,0,0))}var e=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:e.currentPage})},this.flipSpeed)};this.loadImage=function(a,b){var e=a.getContext("2d");e.fillStyle="rgb(255,255,255)";var c=publicationData.page[b].proportions||publicationData.page.defaults.proportions,f=publicationData.size.proportions,h=a.width,g=a.height,d=new Image,l=publicationData.page[b].format||
publicationData.page.defaults.format,k=publicationData.page[b].zoomFormat||publicationData.page.defaults.zoomFormat||publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===l){var m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".jpg";this.loadContent(b,h)}else"js+png"===l?(m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".png",this.loadContent(b,h)):"jpg"===k?m=ASSETS_FOLDER+"/pages/page"+this.getName(b)+"_i2.jpg":"png"===k&&(m=ASSETS_FOLDER+"/pages/page"+
this.getName(b)+"_i2.png");changeUrlWhenPubl(m,function(a){d.src=a});if(c>=f)var q=h,r=(q/c+0.5).toFixed(0),n=0,s=(g-r)/2;else r=g,q=(r*c+0.5).toFixed(0),n=(h-q)/2,s=0;d.onload=function(){ZOOM_LOCK&&el.id("exPage"+b)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+b)},50));e.drawImage(d,n,s,q,r);customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:b,type:1})}};this.addContentDiv=function(){};this.loadContent=function(a,b){var e=ASSETS_FOLDER+"/pages/ios/page"+this.getName(a)+
".js",c=document.getElementsByTagName("head")[0],f=document.createElement("script");f.id="formPrinter";f.type="text/javascript";changeUrlWhenPubl(e,function(a){f.src=a});c.appendChild(f);window.fakeLoadComplete=function(a){window.loadBuffers[a]=window.loadBuffer;for(i in window.loadBuffers[a]){var b=el.add("p");b.style.position="absolute";b.style.fontFamily=window.loadBuffers[a][i][1];b.style.width=2*window.loadBuffers[a][i][2]+"px";b.style.height=2*window.loadBuffers[a][i][3]+"px";b.style.top=2*
window.loadBuffers[a][i][4]+"px";b.style.left=2*window.loadBuffers[a][i][5]+"px";b.style.fontSize=2*window.loadBuffers[a][i][6]+"px";b.style.color=window.loadBuffers[a][i][7];var e=document.createTextNode(window.loadBuffers[a][i][0]);b.appendChild(e);el.id("contentDiv"+a).appendChild(b);customEvents.fireEvent(IOS_LOAD_VECTOR_END,{page:a,type:1})}}};this.getName=function(a){var b="000"+a;9<a&&(b="00"+a);99<a&&(b="0"+a);999<a&&(b=""+a);return b};var c=this,d=-1,n=-1;this.touch=function(){c.block||c.gesture||
ZOOM_LOCK||(d=Modernizr.touch?event.targetTouches[0].pageX:event.pageX)};this.endmove=function(){if(!c.block&&!c.gesture&&!ZOOM_LOCK&&(n=Modernizr.touch?event.changedTouches[0].pageX:event.pageX,-1!=d&&-1!=n)){var a=d-n;70<a?pageMediator.right():-70>a&&pageMediator.left();n=d=-1}};this.gesturestart=function(a){c.gesture=!0;a=c.currentPage;c.gestureDiv=el.id("divPage"+a);customEvents.fireEvent(ZOOM_ANIMATION_START);c.maxZoom=fbUtils.getMaxZoom(c.pageWidth,c.pageHeight);c.gestureDiv.style.top=c.bookTop+
"px";c.gestureDiv.style.left=c.bookLeft+"px";c.gestureDiv.id="exPage"+c.currentPage;HTML5lib.boxShadow(c.gestureDiv,"");HTML5lib.duration(c.gestureDiv,0);c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px)";el.id("mainFrame").appendChild(c.gestureDiv);el.id("videoDiv"+a)&&(el.id("videoDiv"+a).style.opacity=0);c.destroyBook()};this.gesturechange=function(a){1<a.scale&&c.maxZoom>=a.scale&&(c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d("+a.scale+","+a.scale+","+a.scale+
")")};this.gestureend=function(a){var b=c.currentPage;setTimeout(function(){c.gesture=!1},150);var e=c.maxZoom>a.scale?a.scale:c.maxZoom;a=function(){var a=c.pageWidth;publicationData.page[b].wide&&(a/=2);a=a*e/(publicationData.page[b].width||publicationData.page.defaults.width);customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:a,page:b})};1.2>e?(setTimeout(function(){HTML5lib.duration(c.gestureDiv,200);c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d(1.2,1.2,1.2)"},
10),setTimeout(a,210),e=1.2):(c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d("+e+","+e+","+e+")",a())};this.goToZoom=function(a){if(!this.block&&!ZOOM_LOCK){customEvents.fireEvent(ZOOM_ANIMATION_START);el.id("videoDiv"+c)&&(el.id("videoDiv"+c).style.opacity=0);var b=fbUtils.getMaxZoom(this.pageWidth,this.pageHeight),e=this,c=this.currentPage,f=publicationData.page[c].wide,h=el.id("divPage"+this.currentPage);h.style.top=this.bookTop+"px";h.style.left=this.bookLeft+"px";h.style.webkitTransform=
"";h.id="exPage"+c;el.id("videoDiv"+c)&&(el.id("videoDiv"+c).style.opacity=0);el.id("mainFrame").appendChild(h);a=1.5*window.innerWidth/this.pageWidth;a=a>b?b:a;setTimeout(function(){HTML5lib.duration(h,300);HTML5lib.changeOnlyScale(h,a,a,a)},10);var b=publicationData.page[c].width||publicationData.page.defaults.width,g=e.pageWidth;f&&(g/=2);var d=g*a/b;setTimeout(function(){e.destroyBook();customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:d,page:c})},
360)}}}
function TwoPagePublication(s){s=pageTable.getUserIDFromFileID(s||1);this.HORIZONTAL_MARGIN=this.VERTICAL_MARGIN=30;this.bookLeft=this.bookTop=this.bookHeight=this.bookWidth=this.pageHeight=this.pageWidth=0;this.pageBuff=3;this.currentPage={left:0,right:0};this.flipSpeed=1E3;this.loadBuffers={};this.active=this.gesture=this.block=!1;var c=this;this.doubleClick=0;this.currentPage.minus=function(){this.left-=2;this.right-=2};this.currentPage.plus=function(){this.left=1*this.left+2;this.right=1*this.right+
2};this.initSizes=function(){var a=2*publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>a?(this.bookHeight=window.innerHeight-2*this.VERTICAL_MARGIN,this.bookWidth=this.bookHeight*a,this.bookLeft=(window.innerWidth-this.bookWidth)/2,this.bookTop=this.VERTICAL_MARGIN):(this.bookWidth=window.innerWidth-2*this.HORIZONTAL_MARGIN,this.bookHeight=this.bookWidth/a,this.bookLeft=this.HORIZONTAL_MARGIN,this.bookTop=(window.innerHeight-this.bookHeight)/2);this.pageHeight=
this.bookHeight;this.pageWidth=this.bookWidth/2};this.init=function(){var a=this;customEvents.addListener(SHOW_SEARCH_RESULTS,function(){if(a.active)if(publicationData.rtlMode)for(var b=a.currentPage.right-a.pageBuff;b<=1*a.currentPage.left+a.pageBuff;b++)highlight.show(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b));else for(b=a.currentPage.left-a.pageBuff;b<=1*a.currentPage.right+a.pageBuff;b++)highlight.show(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b))});customEvents.addListener(CANCEL_SEARCH,
function(){if(a.active)if(publicationData.rtlMode)for(var b=a.currentPage.right-a.pageBuff;b<=1*a.currentPage.left+a.pageBuff;b++)highlight.hide(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b));else for(b=a.currentPage.left-a.pageBuff;b<=1*a.currentPage.right+a.pageBuff;b++)highlight.hide(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b))});customEvents.addListener(BOOK_FLIPPING_START,function(){a.block=!0});customEvents.addListener(BOOK_FLIPPING_END,function(){a.block=!1});
customEvents.addListener(IOS_LOAD_PAGE_START,function(a){if(2===a.data.type){a=a.data.page;var e=el.add("div");e.id="preloader"+a;e.style.position="absolute";e.style.left="50%";e.style.top="50%";e.style.width="10em";e.style.height="10em";e.style.margin="-3em 0 0 -5em";workspace.preloader.add(e);el.id("pageDiv"+a).appendChild(e)}});customEvents.addListener(IOS_LOAD_BITMAP_END,function(a){2===a.data.type&&el.del("preloader"+a.data.page)});customEvents.addListener(IOS_LOAD_VECTOR_END,function(a){})};
this.drawBook=function(a){this.active=!0;a=a||-10;-10!=a&&this.pageConverter(a);this.initSizes();this.init();a=document.createElement("div");a.id="publicationDiv";a.style.webkitPerspective="3000";a.style.width=this.bookWidth+"px";a.style.height=this.bookHeight+"px";a.style.top=this.bookTop+"px";a.style.left=this.bookLeft+"px";a.style.textAlign="center";a.style.position="absolute";a.style.opacity="1";a.style.zIndex="1000";el.id("mainFrame").appendChild(a);if(publicationData.rtlMode)for(a=this.currentPage.right-
this.pageBuff;a<=1*this.currentPage.left+this.pageBuff;a++)this.drawPage(a);else for(a=this.currentPage.left-this.pageBuff;a<=1*this.currentPage.right+this.pageBuff;a++)this.drawPage(a);1==this.currentPage.right||1==this.currentPage.left?this.drawBookShadow("first"):this.currentPage.left!=publicationData.pageUserCount||publicationData.rtlMode?this.currentPage.right==publicationData.pageUserCount&&publicationData.rtlMode?this.drawBookShadow("last"):this.drawBookShadow("std"):this.drawBookShadow("last")};
this.drawPage=function(a){if(0<a&&a<=publicationData.pageUserCount){var b=0!=a%2?a+"x"+(1*a+1):a-1+"x"+a;if(el.id(b))e=el.id(b);else{var e=el.add("div");e.id=b;e.style.width=this.pageWidth+"px";e.style.height=this.pageHeight+"px";e.style.position="absolute";e.style.webkitTransformStyle="preserve-3d";e.style.webkitTransition="-webkit-transform "+this.flipSpeed+"ms";publicationData.rtlMode?a>=this.currentPage.left?(e.style.left=0,e.style.zIndex=publicationData.pageCount-a,e.style.webkitTransform="rotate3d(0, 1, 0, 0deg)",
e.style.webkitTransformOrigin="100% 100%"):a<=this.currentPage.right&&(e.style.left=this.pageWidth+"px",e.style.zIndex=a,e.style.webkitTransform="rotate3d(0, -1, 0, 0deg)",e.style.webkitTransformOrigin="0% 0%"):a<=this.currentPage.left?(e.style.left=0,e.style.zIndex=a,e.style.webkitTransform="rotate3d(0, 1, 0, 0deg)",e.style.webkitTransformOrigin="100% 100%"):a>=this.currentPage.right&&(e.style.left=this.pageWidth+"px",e.style.zIndex=publicationData.pageCount-a,e.style.webkitTransform="rotate3d(0, -1, 0, 0deg)",
e.style.webkitTransformOrigin="0% 0%")}b=el.add("div");b.id="pageDiv"+a;b.style.position="absolute";b.style.width=this.pageWidth+"px";b.style.height=this.pageHeight+"px";b.style.overflow="hidden";b.className="page";b.style.webkitBackfaceVisibility="hidden";b.style.backgroundColor=publicationData.page[pageTable.getFileIDFromUserID(a)].BGColor||publicationData.page.defaults.BGColor;if(publicationData.rtlMode)if(a>=this.currentPage.left&&0==a%2){b.style.zIndex="-1";var c=-1;b.style.webkitTransform="rotateY(180deg)"}else a>=
this.currentPage.left&&0!=a%2?(b.style.zIndex="1",c=1):a<=this.currentPage.right&&0==a%2?(b.style.zIndex="1",c=1):a<=this.currentPage.right&&0!=a%2&&(b.style.zIndex="-1",c=-1,b.style.webkitTransform="rotateY(180deg)");else a<=this.currentPage.left&&0==a%2?(b.style.zIndex="1",c=1):a<=this.currentPage.left&&0!=a%2?(b.style.zIndex="-1",b.style.webkitTransform="rotateY(180deg)",c=-1):a>=this.currentPage.right&&0==a%2?(b.style.zIndex="-1",b.style.webkitTransform="rotateY(180deg)",c=-1):a>=this.currentPage.right&&
0!=a%2&&(b.style.zIndex="1",c=1);e.appendChild(b);this.drawPageContent(b,a,c);el.id("publicationDiv").appendChild(e);if(publicationData.page[pageTable.getFileIDFromUserID(a)].stub){var f=pageTable.getFileIDFromUserID(a);ZOOM_LOCK&&el.id("exPage"+f)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+f)},50))}else customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:a,type:2})}};this.drawPageContent=function(a,b,e){var c=pageTable.getFileIDFromUserID(b),f=this.pageHeight,
h=publicationData.page[c].wide?2*this.pageWidth:this.pageWidth,g=publicationData.page[c].width||publicationData.page.defaults.width,d=publicationData.page[c].height||publicationData.page.defaults.height,l=g/d;if(h/f>l)var k=f,m=k*l,h=(h-m)/2,f=0;else m=h,k=m/l,h=0,f=(f-k)/2;h=publicationData.rtlMode?0==b%2&&publicationData.page[c].wide?h-this.pageWidth:h:0!=b%2&&publicationData.page[c].wide?h-this.pageWidth:h;l=el.add("canvas");l.id="substraitCanvas"+b;l.width=m;l.height=k;l.style.position="absolute";
l.style.left=h+"px";l.style.top=f+"px";l.style.zIndex=e;l.style.webkitBackfaceVisibility="hidden";a.appendChild(l);var q=m/(2*g),r=publicationData.page[pageTable.getFileIDFromUserID(b)].format||publicationData.page.defaults.format;if("js+jpg"===r||"js+png"===r)r=el.add("div"),r.id="contentDiv"+b,r.style.width=2*g+"px",r.style.height=2*d+"px",r.style.position="absolute",r.style.left=h+"px",r.style.top=f+"px",r.style.webkitTransformOrigin="0% 0%",r.style.webkitTransform="scale("+q+")",r.style.zIndex=
e,a.appendChild(r);1!=b&&(g=el.add("canvas"),g.id="shadow"+b,g.width=100,g.height=this.pageHeight,g.style.position="absolute",g.style.zIndex=e,0==b%2?0==b%2&&b!=publicationData.pageUserCount&&(publicationData.rtlMode?(g.style.left="0px",this.drawRightShadow(g)):(g.style.left=this.pageWidth-100+"px",this.drawLeftShadow(g))):publicationData.rtlMode?(g.style.left=this.pageWidth-100+"px",this.drawLeftShadow(g)):(g.style.left="0px",this.drawRightShadow(g)),a.appendChild(g));g=el.add("canvas");g.id="highlightCanvas"+
b;g.width=m;g.height=k;g.style.position="absolute";g.style.left=h+"px";g.style.top=f+"px";g.style.zIndex=e;a.appendChild(g);highlight.show(pageTable.getFileIDFromUserID(b),g);new LinksLayer(g,pageTable.getFileIDFromUserID(b));if(publicationData.page[c].stub){customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:b,type:2});var n=pageTable.getFileIDFromUserID(b);ZOOM_LOCK&&el.id("exPage"+n)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+n)},50),ZOOM_LOCK=!1)}else this.loadImage(l,
c,b)};this.getName=function(a){var b="000"+a;9<a&&(b="00"+a);99<a&&(b="0"+a);999<a&&(b=""+a);return b};this.loadImage=function(a,b,e){var c=a.getContext("2d");c.fillStyle="rgb(255,255,255)";var f=publicationData.page[b].proportions||publicationData.page.defaults.proportions,h=publicationData.size.proportions,g=a.width;a=a.height;var d=new Image,l=publicationData.page[b].format||publicationData.page.defaults.format,k=publicationData.page[b].zoomFormat||publicationData.page.defaults.zoomFormat||publicationData.page[b].format||
publicationData.page.defaults.format;if("js+jpg"===l){var m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".jpg";this.loadContent(e,g)}else"js+png"===l?(m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".png",this.loadContent(e,g)):"jpg"===k?m=ASSETS_FOLDER+"/pages/page"+this.getName(b)+"_i2.jpg":"png"===k&&(m=ASSETS_FOLDER+"/pages/page"+this.getName(b)+"_i2.png");changeUrlWhenPubl(m,function(a){d.src=a});if(f>=h)var q=g,r=(q/f+0.5).toFixed(0),n=0,s=(a-r)/2;else r=a,q=(r*f+0.5).toFixed(0),
n=(g-q)/2,s=0;d.onload=function(){ZOOM_LOCK&&el.id("exPage"+b)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+b)},50));fileID=null;c.drawImage(d,n,s,q,r);customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:e,type:2})}};this.loadContent=function(a,b){var e=pageTable.getFileIDFromUserID(a),e=ASSETS_FOLDER+"/pages/ios/page"+this.getName(e)+".js",c=document.getElementsByTagName("head")[0],f=document.createElement("script");f.id="formPrinter";f.type="text/javascript";
changeUrlWhenPubl(e,function(a){f.src=a});c.appendChild(f);window.fakeLoadComplete=function(a){window.loadBuffers[a]=window.loadBuffer;for(i in window.loadBuffers[a]){var b=el.add("p");b.style.position="absolute";b.style.fontFamily=window.loadBuffers[a][i][1];b.style.width=2*window.loadBuffers[a][i][2]+"px";b.style.height=2*window.loadBuffers[a][i][3]+"px";b.style.top=2*window.loadBuffers[a][i][4]+"px";b.style.left=2*window.loadBuffers[a][i][5]+"px";b.style.fontSize=2*window.loadBuffers[a][i][6]+
"px";b.style.color=window.loadBuffers[a][i][7];var e=document.createTextNode(window.loadBuffers[a][i][0]);b.appendChild(e);e=pageTable.getUserIDFromFileID(a);el.id("contentDiv"+e).appendChild(b)}}};this.destroyPage=function(a){el.del(a)};this.clearPage=function(a){el.id("substraitCanvas"+a)&&el.del("substraitCanvas"+a);el.id("contentDiv"+a)&&el.del("contentDiv"+a);el.id("highlightCanvas"+a)&&el.del("highlightCanvas"+a)};this.goToPage=function(a){a=pageTable.getUserIDFromFileID(a);if(publicationData.rtlMode)if(a>=
this.currentPage.right-2&&a<this.currentPage.right){var b=1*this.currentPage.right+3+"x"+(1*this.currentPage.left+3);el.id(b)&&this.destroyPage(b);this.shiftLeft();this.currentPage.minus();this.drawPage(1*this.currentPage.left-this.pageBuff);this.drawPage(1*this.currentPage.right-this.pageBuff)}else if(a<=1*this.currentPage.left+2&&a>this.currentPage.left)b=1*this.currentPage.right-3+"x"+(1*this.currentPage.left-3),el.id(b)&&this.destroyPage(b),this.shiftRight(),this.currentPage.plus(),this.drawPage(1*
this.currentPage.left+this.pageBuff),this.drawPage(1*this.currentPage.right+this.pageBuff);else{if(a!=this.currentPage.left&&a!=this.currentPage.right){a<this.currentPage.right?(this.clearPage(1*this.currentPage.right-1),this.clearPage(1*this.currentPage.right-2),this.shiftLeft()):(this.clearPage(1*this.currentPage.left+1),this.clearPage(1*this.currentPage.left+2),this.shiftRight());this.pageConverter(a);var e=this;setTimeout(function(){e.destroyBook();e.drawBook(a)},this.flipSpeed)}}else a<=this.currentPage.right+
2&&a>this.currentPage.right?(this.shiftLeft(),b=1*this.currentPage.left-3+"x"+(1*this.currentPage.right-3),this.currentPage.plus(),el.id(b)&&this.destroyPage(b),this.drawPage(1*this.currentPage.left+this.pageBuff),this.drawPage(1*this.currentPage.right+this.pageBuff)):a>=this.currentPage.left-2&&a<this.currentPage.left?(this.shiftRight(),b=1*this.currentPage.left+3+"x"+(1*this.currentPage.right+3),this.currentPage.minus(),el.id(b)&&this.destroyPage(b),this.drawPage(1*this.currentPage.left-this.pageBuff),
this.drawPage(1*this.currentPage.right-this.pageBuff)):a!=this.currentPage.left&&a!=this.currentPage.right&&(a>this.currentPage.right?(this.clearPage(1*this.currentPage.right+1),this.clearPage(1*this.currentPage.right+2),this.shiftLeft()):(this.clearPage(1*this.currentPage.left-1),this.clearPage(1*this.currentPage.left-2),this.shiftRight()),this.pageConverter(a),e=this,setTimeout(function(){e.destroyBook();e.drawBook(a)},this.flipSpeed))};this.shiftLeft=function(){if(publicationData.rtlMode)var a=
1*this.currentPage.right-1+"x"+this.currentPage.right,b=publicationData.pageCount-this.currentPage.right,e=89999+this.currentPage.right;else a=this.currentPage.right+"x"+(1*this.currentPage.right+1),b=this.currentPage.right,e=1E5-this.currentPage.right;var c=el.id(a);customEvents.fireEvent(BOOK_FLIPPING_START);c.style.webkitTransform="rotate3d(0, -1, 0, 0deg)"==c.style.webkitTransform?"rotate3d(0, -1, 0, 179."+e+"deg)":"rotate3d(0, 1, 0, 0deg)";var f=this;setTimeout(function(){c.style.zIndex=b;for(var a=
c.getElementsByTagName("*"),e=0;e<a.length;e++){var f=a[e].style.zIndex;a[e].style.zIndex=1==f?-1:100==f?-100:-100==f?100:1}},this.flipSpeed/3);var f=this,d=f.currentPage.right;publicationData.rtlMode?(2==d&&f.drawBookShadow("first"),f=this,a=function(){d==publicationData.pageUserCount&&f.drawBookShadow("std");if(0<f.currentPage.left&&f.currentPage.right<=publicationData.pageUserCount)var a=[f.currentPage.left,f.currentPage.right];else 0>=f.currentPage.left?a=[f.currentPage.right]:f.currentPage.right>
publicationData.pageUserCount&&(a=[f.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:a})}):(d==publicationData.pageUserCount-1&&f.drawBookShadow("last"),f=this,a=function(){1==d&&f.drawBookShadow("std");if(0<f.currentPage.left&&f.currentPage.right<=publicationData.pageUserCount)var a=[f.currentPage.left,f.currentPage.right];else 0>=f.currentPage.left?a=[f.currentPage.right]:f.currentPage.right>publicationData.pageUserCount&&(a=[f.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,
{page:a})});setTimeout(a,this.flipSpeed)};this.shiftRight=function(){var a=this;if(publicationData.rtlMode)var b=this.currentPage.left+"x"+(1*this.currentPage.left+1),e=this.currentPage.left,c=1E5-this.currentPage.left;else b=1*this.currentPage.left-1+"x"+this.currentPage.left,e=publicationData.pageCount-this.currentPage.left,c=89999+this.currentPage.right;var f=el.id(b);customEvents.fireEvent(BOOK_FLIPPING_START);f.style.webkitTransform="rotate3d(0, 1, 0, 0deg)"==f.style.webkitTransform?"rotate3d(0, 1, 0, 179."+
c+"deg)":"rotate3d(0, -1, 0, 0deg)";a=this;setTimeout(function(){for(var a=f.getElementsByTagName("*"),b=0;b<a.length;b++){var c=a[b].style.zIndex;a[b].style.zIndex=1==c?-1:100==c?-100:-100==c?100:1}f.style.zIndex=e},this.flipSpeed/3);var d=a.currentPage.left;publicationData.rtlMode?(d==publicationData.pageUserCount-1&&a.drawBookShadow("last"),a=this,b=function(){1==d&&a.drawBookShadow("std");if(0<a.currentPage.left&&a.currentPage.right<=publicationData.pageUserCount)var b=[a.currentPage.left,a.currentPage.right];
else 0>=a.currentPage.left?b=[a.currentPage.right]:a.currentPage.right>publicationData.pageUserCount&&(b=[a.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:b})}):(2==d&&a.drawBookShadow("first"),a=this,b=function(){d==publicationData.pageUserCount&&a.drawBookShadow("std");if(0<a.currentPage.left&&a.currentPage.right<=publicationData.pageUserCount)var b=[a.currentPage.left,a.currentPage.right];else 0>=a.currentPage.left?b=[a.currentPage.right]:a.currentPage.right>publicationData.pageUserCount&&
(b=[a.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:b})});setTimeout(b,this.flipSpeed)};var d=-1,n=-1,c=this;this.touch=function(){c.block||c.gesture||ZOOM_LOCK||(d=Modernizr.touch?event.targetTouches[0].pageX:event.pageX)};this.endmove=function(){if(!c.block&&!c.gesture&&!ZOOM_LOCK&&(n=Modernizr.touch?event.changedTouches[0].pageX:event.pageX,-1!=d&&-1!=n)){var a=d-n;70<a?pageMediator.right():-70>a&&pageMediator.left();n=d=-1}};this.gesturestart=function(a){c.gestureStartTrigg=
!0;customEvents.fireEvent(ZOOM_ANIMATION_START);c.gesture=!0;a=a.target.id.match(/\d+/i);var b=pageTable.getFileIDFromUserID(a);publicationData.page[b].wide&&0!=a%2&&!publicationData.rtlMode&&(a-=1);publicationData.page[b].wide&&0===a%2&&publicationData.rtlMode&&(a=1*a+1);c.gestureDiv=el.id("pageDiv"+a);c.gesturePage=a;c.maxZoom=publicationData.page[b].wide?fbUtils.getMaxZoom(c.bookWidth,c.pageHeight):fbUtils.getMaxZoom(c.pageWidth,c.pageHeight);el.id("mainFrame").appendChild(c.gestureDiv);el.del("shadow"+
a);c.gestureDiv.style.webkitTransform="";c.gestureDiv.style.zIndex=1E5;c.gestureDiv.id="exPage"+b;c.gestureDiv.style.top=c.bookTop+"px";c.gestureDiv.style.webkitTransformOrigin="50% 50%";publicationData.page[b].wide&&(c.gestureDiv.style.width=2*c.pageWidth+"px");publicationData.rtlMode&&0===a%2?c.gestureDiv.style.left=c.bookLeft+c.pageWidth+"px":publicationData.rtlMode||0!==a%2?publicationData.rtlMode||0==a%2?publicationData.rtlMode&&0!=a%2&&(c.gestureDiv.style.left=c.bookLeft+"px"):c.gestureDiv.style.left=
c.bookLeft+c.pageWidth+"px":c.gestureDiv.style.left=c.bookLeft+"px"};this.gesturechange=function(a){1<a.scale&&c.maxZoom>=a.scale&&(c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d("+a.scale+","+a.scale+","+a.scale+")")};this.gestureend=function(a){if(c.gestureStartTrigg){c.gestureStartTrigg=!1;var b=1.3;setTimeout(function(){c.gesture=!1},150);var e=pageTable.getFileIDFromUserID(c.gesturePage);pageMediator.changePage(e);var d=c.gesturePage;a=a.scale>c.maxZoom?c.maxZoom:a.scale;
a<b&&(a=b);var f=c.pageWidth*a/(publicationData.page[e].width||publicationData.page.defaults.width);c.destroyBook();c.gestureDiv.style.webkitTransitionDuration="300ms";if(publicationData.rtlMode&&0===d%2)var h=-c.pageWidth/2;else publicationData.rtlMode||0!==d%2?publicationData.rtlMode||0==d%2?publicationData.rtlMode&&0!=d%2&&(h=c.pageWidth/2):h=-c.pageWidth/2:h=c.pageWidth/2;publicationData.page[e].wide&&(h=0);(b=a)?(c.gestureDiv.style.webkitTransitionDuration="300ms",c.gestureDiv.style.webkitTransform=
"translate3d("+h+"px, 0px, 0px) scale3d("+a+","+a+","+a+")",setTimeout(function(){customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:f,page:e})},310)):(c.gestureDiv.style.webkitTransform="translate3d("+h+"px, 0px, 0px) scale3d("+a+","+a+","+a+")",customEvents.fireEvent(START_ZOOM_PRELOADER),customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:f,page:e}))}};this.destroyBook=function(){el.del("publicationDiv");this.active=!1};this.pageConverter=function(a){publicationData.rtlMode?
0!=a%2?(this.currentPage.left=a,this.currentPage.right=a-1):(this.currentPage.left=1*a+1,this.currentPage.right=a):0!=a%2?(this.currentPage.left=a-1,this.currentPage.right=a):(this.currentPage.left=a,this.currentPage.right=1*a+1);this.currentPage.left*=1;this.currentPage.right*=1};this.pageConverter(s);this.drawBookShadow=function(a){var b=publicationData.pageUserCount+"x"+publicationData.pageUserCount,e=publicationData.pageUserCount-3+"x"+(publicationData.pageUserCount-2);"first"==a?(el.id("3x4")?
HTML5lib.boxShadow(el.id("3x4"),"0px 0px 3px #000"):HTML5lib.boxShadow(el.id("1x2"),"0px 0px 3px #000"),HTML5lib.boxShadow(el.id("publicationDiv"),"0px 0px 0px #000")):"last"==a?(el.id(e)?HTML5lib.boxShadow(el.id(e),"0px 0px 3px #000"):HTML5lib.boxShadow(el.id(b),"0px 0px 3px #000"),HTML5lib.boxShadow(el.id("publicationDiv"),"0px 0px 0px #000")):(HTML5lib.boxShadow(el.id("publicationDiv"),"0px 0px 3px #000"),el.id(e)?HTML5lib.boxShadow(el.id(e),"0px 0px 0px #000"):el.id(b)?HTML5lib.boxShadow(el.id(b),
"0px 0px 0px #000"):el.id("pageDiv3")?HTML5lib.boxShadow(el.id("3x4"),"0px 0px 0px #000"):el.id("pageDiv1")&&HTML5lib.boxShadow(el.id("1x2"),"0px 0px 0px #000"))};this.goToZoom=function(a){if(!this.block&&!ZOOM_LOCK){var b=pageTable.getFileIDFromUserID(a);maxZoom=publicationData.page[b].wide?fbUtils.getMaxZoom(this.bookWidth,this.pageHeight):fbUtils.getMaxZoom(this.pageWidth,this.pageHeight);pageMediator.changePage(b);customEvents.fireEvent(ZOOM_ANIMATION_START);publicationData.page[b].wide&&0!=a%
2&&!publicationData.rtlMode&&(a-=1);publicationData.page[b].wide&&0==a%2&&publicationData.rtlMode&&(a=1*a+1);var e=el.id("pageDiv"+a);el.id("mainFrame").appendChild(e);e.style.webkitTransform="";e.style.zIndex=99999;e.id="exPage"+b;e.style.top=this.bookTop+"px";publicationData.rtlMode&&0===a%2?e.style.left=this.bookLeft+this.pageWidth+"px":publicationData.rtlMode||0!==a%2?publicationData.rtlMode||0==a%2?publicationData.rtlMode&&0!=a%2&&(e.style.left=this.bookLeft+"px"):e.style.left=this.bookLeft+
this.pageWidth+"px":e.style.left=this.bookLeft+"px";el.del("shadow"+a);publicationData.page[b].wide&&(e.style.width=2*this.pageWidth+"px");var c=window.innerWidth/(publicationData.page[b].wide?this.bookWidth:this.pageWidth),c=c>maxZoom?maxZoom:c,f=this,d=function(){e.style.webkitTransitionDuration="300ms";e.style.webkitBackfaceVisibility="";publicationData.page[b].wide||(e.style.left=f.bookLeft+f.pageWidth/2+"px");e.style.webkitTransformOrigin="50% 50%";e.style.webkitTransform="translate3d(0px,0px,10px) scale3d("+
c+","+c+","+c+")";d=null};setTimeout(d,10);var g=f.pageWidth*c/(publicationData.page[b].width||publicationData.page.defaults.width);setTimeout(function(){f.destroyBook();customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:g,page:b})},350)}};this.drawLeftShadow=function(a){ctx=a.getContext("2d");var b=ctx.createLinearGradient(0,0,100,0);b.addColorStop(0,"rgba(0,0,0,0)");b.addColorStop(0.6,"rgba(0,0,0,0.1)");b.addColorStop(0.95,"rgba(0,0,0,0.2)");b.addColorStop(1,
"rgba(0,0,0,0.65)");ctx.fillStyle=b;ctx.fillRect(0,0,a.width,a.height)};this.drawRightShadow=function(a){ctx=a.getContext("2d");var b=ctx.createLinearGradient(this.bookWidth/20,0,0,0);b.addColorStop(0,"rgba(0,0,0,0.0)");b.addColorStop(0.4,"rgba(0,0,0,0.05)");b.addColorStop(0.8,"rgba(0,0,0,0.20)");b.addColorStop(1,"rgba(0,0,0,0.15)");ctx.fillStyle=b;ctx.fillRect(0,0,a.width,a.height)}}
function ZoomIOSPublication(s){this.bookHeight=this.bookWidth=this.pageHeight=this.pageWidth=0;this.pageShift=20;this.active=!1;this.currentPage=s||1;this.pageBuff=0;this.flipSpeed=500;this.loadBuffers={};this.gesture=!1;this.zoomFactor=this.translateScrollY=this.translateScrollX=0;this.zoomIOSpeed=500;this.scrollbars=this.block=this.active=!1;this.scrolls={};this.init=function(){var a=this;customEvents.addListener(SHOW_SEARCH_RESULTS,function(){if(a.active){highlight.show(a.currentPage);for(var b=
a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.show(b)}});customEvents.addListener(CANCEL_SEARCH,function(){if(a.active){highlight.hide(a.currentPage);for(var b=a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.hide(b)}});customEvents.addListener(BOOK_FLIPPING_START,function(){a.block=!0});customEvents.addListener(BOOK_FLIPPING_END,function(){a.block=!1});customEvents.addListener(ROTATE_DEVICE,function(){a.active&&a.rotate()});
customEvents.addListener(IOS_LOAD_PAGE_START,function(a){if(3===a.data.type){a=a.data.page;var c=el.add("div");c.id="preloader"+a;c.style.position="absolute";c.style.left=window.innerWidth/2+"px";c.style.top=window.innerHeight/2+"px";c.style.width="10em";c.style.height="10em";c.style.margin="-3em 0 0 -5em";workspace.preloader.add(c);el.id("page"+a).appendChild(c)}});customEvents.addListener(IOS_LOAD_BITMAP_END,function(a){3===a.data.type&&el.del("preloader"+a.data.page)});customEvents.addListener(IOS_LOAD_VECTOR_END,
function(a){})};this.initSizes=function(a,b){this.zoomFactor=a=a||this.zoomFactor;b=b||this.currentPage;var c=publicationData.size.width/publicationData.size.height;this.pageWidth=(publicationData.page[b].width||publicationData.page.defaults.width)*a;this.pageHeight=this.pageWidth/c;this.pageLeft=(window.innerWidth-this.pageWidth)/2;this.pageTop=(window.innerHeight-this.pageHeight)/2;this.widePageWidth=2*this.pageWidth;this.widePageLeft=(window.innerWidth-this.widePageWidth)/2};this.drawBook=function(a,
b){b=b||!1;this.active=!0;this.currentPage=a;this.init();var c=el.add("div");c.id="zoomBook";c.style.width="100%";c.style.height="100%";c.style.position="absolute";el.id("mainFrame").appendChild(c);for(c=this.currentPage-this.pageBuff;c<=1*this.currentPage+this.pageBuff;c++)0<c&&c<=publicationData.pageCount&&this.drawPage(c,b)};this.drawPage=function(a,b){var c=publicationData.page[a].wide;b=c?b||{x:this.widePageLeft,y:this.pageTop}:b||{x:this.pageLeft,y:this.pageTop};var d=el.add("div");d.id="pageMask"+
a;d.style.position="absolute";d.style.width="100%";d.style.height="100%";d.style.webkitTransform="translate3d("+(publicationData.rtlMode?(this.currentPage-a)*window.innerWidth:(a-this.currentPage)*window.innerWidth)+"px,0px,0px)";var f=el.add("div");f.id="page"+a;f.style.position="absolute";f.style.overflow="hidden";f.style.width=c?this.widePageWidth+"px":this.pageWidth+"px";f.style.height=this.pageHeight+"px";HTML5lib.boxShadow(f,"0px 0px 3px #000");"photo_album"!=publicationData.type&&"document"!=
publicationData.type&&(f.style.backgroundColor=publicationData.page[a].BGColor||publicationData.page.defaults.BGColor);0<this.pageTop&&(f.style.top=this.pageTop+"px");c?0<this.widePageLeft&&(f.style.left=this.widePageLeft+"px"):0<this.pageLeft&&(f.style.left=this.pageLeft+"px");d.appendChild(f);el.id("zoomBook").appendChild(d);var h=this.injectCanvas(f,a),f=null;this.scrolls[a]=new iScroll("pageMask"+a,{hScrollbar:this.scrollbars,vScrollbar:this.scrollbars,zoom:!1});b.y=0==b.y?b.y-h:b.y;this.scrolls[a].scrollTo(b.x,
b.y,0);var g=this,p=c?this.widePageWidth:this.pageWidth;this.slideMode=p>window.innerWidth?!0:!1;var l=function(){g.slideMode&&(150<g.scrolls[a].x&&(1!=g.currentPage&&!publicationData.rtlMode||g.currentPage!=publicationData.pageCount&&publicationData.rtlMode)?(pageMediator.left(),Modernizr.touch?el.id("pageMask"+a).removeEventListener("touchmove",l):el.id("pageMask"+a).removeEventListener("mousemove",l),g.scrolls[a].destroy()):g.scrolls[a].x<window.innerWidth-p-150&&(g.currentPage!=publicationData.pageCount&&
!publicationData.rtlMode||1!=g.currentPage&&publicationData.rtlMode)&&(pageMediator.right(),Modernizr.touch?el.id("pageMask"+a).removeEventListener("touchmove",l):el.id("pageMask"+a).removeEventListener("mousemove",l),g.scrolls[a].destroy()))};Modernizr.touch?d.addEventListener("touchmove",l):d.addEventListener("mousemove",l);d=null};this.injectCanvas=function(a,b){var c=publicationData.page[b].wide,d=this.pageHeight,f=publicationData.page[b].width||publicationData.page.defaults.width,h=publicationData.page[b].height||
publicationData.page.defaults.height,g=f/h,p=c?this.widePageWidth:this.pageWidth;if((c?this.widePageWidth/d:this.pageWidth/d)>g)var c=d,l=c*g,g=(p-l)/2,d=0;else l=p,c=l/g,g=0,d=(d-c)/2;var d=d.toFixed(0),p=(c/3).toFixed(0),k=el.add("canvas");k.id="1substraitCanvas"+b;k.width=l;k.height=p;k.style.position="absolute";k.style.left=g+"px";k.style.top=d+"px";k.style.webkitTransform="translate3d(0,0,0)";a.appendChild(k);k=el.add("canvas");k.id="2substraitCanvas"+b;k.width=l;k.height=p;k.style.position=
"absolute";k.style.left=g+"px";k.style.top=1*d+1*p-0.1+"px";k.style.webkitTransform="translate3d(0,0,0)";a.appendChild(k);k=el.add("canvas");k.id="3substraitCanvas"+b;k.width=l;k.height=c-2*p;k.style.position="absolute";k.style.left=g+"px";k.style.top=1*d+2*p-1.1+"px";k.style.webkitTransform="translate3d(0,0,0)";a.appendChild(k);publicationData.page[b].stub?(customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:b,type:3}),ZOOM_LOCK&&el.id("exPage"+b)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+
b)},150))):(customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:b,type:3}),this.loadImage(c,p,b));p=l/(2*f);k=publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===k||"js+png"===k)k=el.add("div"),k.id="zContentDiv"+b,k.style.width=2*f+"px",k.style.height=2*h+"px",k.style.position="absolute",k.style.left=g+"px",k.style.top=d+"px",k.style.webkitTransformOrigin="0% 0%",k.style.webkitTransform="scale("+p+")",a.appendChild(k);var m=el.add("canvas");m.id="highlightCanvas"+b;m.width=
l;m.height=c;m.style.position="absolute";m.style.left=g+"px";m.style.top=d+"px";m.style.opacity=0;a.appendChild(m);var q=function(){m.style.opacity=1;customEvents.removeListener(IOS_LOAD_BITMAP_END,q)};customEvents.addListener(IOS_LOAD_BITMAP_END,q);new LinksLayer(m,b);highlight.show(b,m);return d};this.loadImage=function(a,b,c){var d=el.id("1substraitCanvas"+c),f=d.getContext("2d");f.fillStyle="rgb(255,255,255)";var d=el.id("2substraitCanvas"+c),h=d.getContext("2d");h.fillStyle="rgb(255,255,255)";
var d=el.id("3substraitCanvas"+c),g=d.getContext("2d");g.fillStyle="rgb(255,255,255)";var p=publicationData.page[c].proportions||publicationData.page.defaults.proportions,l=publicationData.size.proportions,d=d.width,k=new Image,m=publicationData.page[c].format||publicationData.page.defaults.format,q=publicationData.page[c].zoomFormat||publicationData.page.defaults.zoomFormat||publicationData.page[c].format||publicationData.page.defaults.format;if("js+jpg"===m){var r=COMMON_FOLDER+"/page-substrates/page"+
this.getName(c)+".jpg";this.loadContent(c,d)}else"js+png"===m?(r=COMMON_FOLDER+"/page-substrates/page"+this.getName(c)+".png",this.loadContent(c,d)):"jpg"===q?r=ASSETS_FOLDER+"/pages/page"+this.getName(c)+"_i2.jpg":"png"===q&&(r=ASSETS_FOLDER+"/pages/page"+this.getName(c)+"_i2.png");changeUrlWhenPubl(r,function(a){k.src=a});if(p>=l)var n=d,p=(n/p).toFixed(0),s=0,p=(a-p)/2;else n=(a*p).toFixed(0),s=(d-n)/2,p=0;var t=p>b?b:p,u=p>2*b?2*b:t-b,t=p,u=t-b,v=t+u-b;k.onload=function(){customEvents.fireEvent(IOS_LOAD_BITMAP_END,
{page:c,type:3});f.drawImage(k,s,t,n,a);h.drawImage(k,s,u,n,a);g.drawImage(k,s,v,n,a);setTimeout(function(){ZOOM_LOCK&&el.id("exPage"+c)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+c)},150))},300)}};this.loadContent=function(a,b){var c=ASSETS_FOLDER+"/pages/ios/page"+this.getName(a)+".js",d=document.getElementsByTagName("head")[0],f=document.createElement("script");f.id="formPrinter";f.type="text/javascript";changeUrlWhenPubl(c,function(a){f.src=a});d.appendChild(f);
window.fakeLoadComplete=function(a){window.loadBuffers[a]=window.loadBuffer;for(i in window.loadBuffers[a]){var b=el.add("p");b.style.position="absolute";b.style.fontFamily=window.loadBuffers[a][i][1];b.style.width=2*window.loadBuffers[a][i][2]+"px";b.style.height=2*window.loadBuffers[a][i][3]+"px";b.style.top=2*window.loadBuffers[a][i][4]+"px";b.style.left=2*window.loadBuffers[a][i][5]+"px";b.style.fontSize=2*window.loadBuffers[a][i][6]+"px";b.style.color=window.loadBuffers[a][i][7];var c=document.createTextNode(window.loadBuffers[a][i][0]);
b.appendChild(c);el.id("zContentDiv"+a).appendChild(b);customEvents.fireEvent(IOS_LOAD_VECTOR_END,{page:a,type:3})}}};this.rotate=function(){this.initSizes();0<this.pageLeft?el.id("page"+this.currentPage).style.left=publicationData.page[this.currentPage].wide?this.widePageLeft+"px":this.pageLeft+"px":el.id("page"+this.currentPage).style.left="0px";0<this.pageTop?el.id("page"+this.currentPage).style.top=this.pageTop+"px":el.id("page"+this.currentPage).style.top="0px"};this.slideLeft=function(a){var b=
el.id("pageMask"+this.currentPage);a=el.id("pageMask"+a);b.style.webkitTransitionDuration="300ms";a.style.webkitTransitionDuration="300ms";b.style.webkitTransform="translate3d("+-window.innerWidth+"px,0px,0px)";a.style.webkitTransform="translate3d(0px,0px,0px)";var c=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:c.currentPage})},300)};this.slideRight=function(a){var b=el.id("pageMask"+this.currentPage);a=el.id("pageMask"+a);b.style.webkitTransitionDuration="300ms";a.style.webkitTransitionDuration=
"300ms";b.style.webkitTransform="translate3d("+window.innerWidth+"px,0px,0px)";a.style.webkitTransform="translate3d(0px,0px,0px)";var c=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:c.currentPage})},300)};this.goToPage=function(a){if(this.currentPage<a){this.drawPage(a,{x:0,y:0});publicationData.rtlMode?this.slideRight(a):this.slideLeft(a);var b=this.currentPage;this.currentPage=a;var c=this;setTimeout(function(){c.destroyPage(b)},300)}else this.currentPage>a&&(this.drawPage(a,
{x:0,y:0}),publicationData.rtlMode?this.slideLeft(a):this.slideRight(a),b=this.currentPage,this.currentPage=a,c=this,setTimeout(function(){c.destroyPage(b)},300))};this.destroyPage=function(a){this.scrolls[a].destroy();delete this.scrolls[a];el.del("page"+a);el.del("pageMask"+a)};this.destroyBook=function(){el.del("zoomBook");this.active=!1};this.goToOnePage=function(){if(!ZOOM_LOCK){customEvents.fireEvent(ZOOM_ANIMATION_START);el.id("videoDiv"+a)&&(el.id("videoDiv"+a).style.opacity=0);var a=this.currentPage,
b=publicationData.page[a].wide,c=this;this.scrolls[a].destroy();delete this.scrolls[a];var d=publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>d?oneBookHeight=window.innerHeight-20:(oneBookWidth=window.innerWidth-20,oneBookHeight=oneBookWidth/d);b&&(oneBookHeight/=2);var f=oneBookHeight/this.pageHeight,h=el.id("page"+a);h.style.webkitTransformOrigin="50% 50%";el.id("mainFrame").appendChild(h);h.style.webkitTransform="";h.id="exPage"+a;h.style.zIndex="100000";
h.style.webkitBoxShadow="";setTimeout(function(){h.style.webkitTransitionDuration="300ms";h.style.top=c.pageTop+"px";h.style.left=b?c.widePageLeft+"px":c.pageLeft+"px";HTML5lib.changeOnlyScale(h,f,f,f)},20);setTimeout(function(){c.destroyBook();customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END_TO_ONE,{page:a})},320)}};this.goToTwoPage=function(){if(!ZOOM_LOCK){customEvents.fireEvent(ZOOM_ANIMATION_START);el.id("videoDiv"+a)&&(el.id("videoDiv"+a).style.opacity=
0);var a=this.currentPage,b=publicationData.page[a].wide,c=this,d=pageTable.getUserIDFromFileID(a);this.scrolls[a].destroy();this.scrolls[a]=null;var f=2*publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>f?(twoBookHeight=window.innerHeight-60,twoBookWidth=twoBookHeight*f):(twoBookWidth=window.innerWidth-60,twoBookHeight=twoBookWidth/f);var h=0;publicationData.rtlMode&&0===d%2?h=twoBookWidth/4:publicationData.rtlMode&&0!=d%2?h=-twoBookWidth/4:publicationData.rtlMode||
0!==d%2?publicationData.rtlMode||0==d%2||(h=twoBookWidth/4):h=-twoBookWidth/4;var g=twoBookHeight/this.pageHeight,p=el.id("page"+a);p.style.webkitTransformOrigin="50% 50%";el.id("mainFrame").appendChild(p);p.style.webkitTransform="";p.id="exPage"+a;p.style.zIndex="100000";p.style.webkitBoxShadow="";b&&(h=0);setTimeout(function(){p.style.webkitTransitionDuration="300ms";p.style.top=c.pageTop+"px";p.style.left=b?c.widePageLeft+"px":c.pageLeft+"px";p.style.webkitTransform="translate3d("+h+"px,0,0) scale3d("+
g+","+g+","+g+")";customEvents.fireEvent(START_ZOOM_PRELOADER,{shift:h})},20);setTimeout(function(){c.destroyBook();customEvents.fireEvent(ZOOM_ANIMATION_END_TO_TWO,{page:d})},320)}};this.getName=function(a){var b="000"+a;9<a&&(b="00"+a);99<a&&(b="0"+a);999<a&&(b=""+a);return b};var c=this;this.gesturestart=function(a){customEvents.fireEvent(ZOOM_ANIMATION_START);el.id("videoDiv"+page)&&(el.id("videoDiv"+page).style.opacity=0);c.gesture=!0;c.zoomPage=c.currentPage;c.x=c.scrolls[c.zoomPage].x;c.y=
c.scrolls[c.zoomPage].y;c.scrolls[c.zoomPage].destroy();c.scrolls[c.zoomPage]=null;c.zoomDiv=el.id("page"+c.zoomPage);c.maxZoom=fbUtils.getMaxZoom(publicationData.page[c.zoomPage].wide?2*c.pageWidth:c.pageWidth,c.pageHeight);if(1===orientationObserver.getType()){var b=window.innerWidth/window.innerHeight,d=publicationData.size.width/publicationData.size.height;b>d?oneBookHeight=window.innerHeight-20:(oneBookWidth=window.innerWidth-20,oneBookHeight=oneBookWidth/d);c.minZoom=oneBookHeight/c.pageHeight;
publicationData.page[c.zoomPage].wide&&(c.minZoom=oneBookHeight/2/c.pageHeight)}else b=window.innerWidth/window.innerHeight,d=2*publicationData.size.width/publicationData.size.height,b>d?(twoBookHeight=window.innerHeight-60,c.twoBookWidth=twoBookHeight*d):(c.twoBookWidth=window.innerWidth-60,twoBookHeight=c.twoBookWidth/d),c.minZoom=twoBookHeight/c.pageHeight;for(i in c.zoomDiv.getElementsByTagName("*"))c.zoomDiv.getElementsByTagName("*")[i].id="";el.id("mainFrame").appendChild(c.zoomDiv);c.zoomDiv.id=
"exPage"+c.zoomPage;c.zoomDiv.style.zIndex="100000";0>=c.pageTop?(c.zoomDiv.style.top=c.y+"px",b=(-c.y+a.pageY).toFixed(0)):b=(a.pageY-c.pageTop).toFixed(0);d=publicationData.page[c.zoomPage].wide?c.widePageLeft:c.pageLeft;0>=d?(c.zoomDiv.style.left=c.x+"px",a=(-c.x+a.pageX).toFixed(0)):a=(a.pageX-d).toFixed(0);c.zoomDiv.style.webkitTransformOrigin=a+"px "+b+"px";c.destroyBook()};this.gesturechange=function(a){c.minZoom<=a.scale&&c.maxZoom>=a.scale&&(c.zoomDiv.style.webkitTransform="scale3d("+a.scale+
","+a.scale+","+a.scale+")")};this.gestureend=function(a){setTimeout(function(){c.gesture=!1},150);var b=a.scale>c.maxZoom?c.maxZoom:a.scale<c.minZoom?c.minZoom:a.scale;c.zoomDiv.style.webkitTransform="scale3d("+b+","+b+","+b+")";var d=c.pageHeight*b,n=publicationData.page[c.zoomPage].wide?2*c.pageWidth*b:c.pageWidth*b;a=publicationData.page[c.zoomPage].width||publicationData.page.defaults.width;publicationData.page[c.zoomPage].wide&&(a*=2);var f=n/a,h=0>=c.zoomDiv.getBoundingClientRect().left?c.zoomDiv.getBoundingClientRect().left:
0,g=0>=c.zoomDiv.getBoundingClientRect().top?c.zoomDiv.getBoundingClientRect().top:0,p=c.zoomDiv.getBoundingClientRect().top,l=window.innerHeight-c.zoomDiv.getBoundingClientRect().bottom,k=c.zoomDiv.getBoundingClientRect().left,m=window.innerWidth-c.zoomDiv.getBoundingClientRect().right,q=a=0;c.zoomDiv.style.webkitTransitionDuration="100ms";d<=window.innerHeight?q=(window.innerHeight-d)/2-p:d>window.innerHeight&&0<p?q=-p:d>window.innerHeight&&0<l&&(q=l);n<=window.innerWidth?a=(window.innerWidth-n)/
2-k:n>window.innerWidth&&0<m?a=0:n>window.innerWidth&&0<k&&(a=-k);var r={x:h,y:g},d=0;b<=c.minZoom&&2===orientationObserver.getType()?(n=pageTable.getUserIDFromFileID(c.zoomPage),publicationData.rtlMode||0!==n%2?publicationData.rtlMode||0==n%2?publicationData.rtlMode&&0===n%2?d=-c.twoBookWidth/4:publicationData.rtlMode&&0!=n%2&&(d=c.twoBookWidth/4):d=-c.twoBookWidth/4:d=c.twoBookWidth/4,publicationData.page[c.zoomPage].wide&&(d=0),c.zoomDiv.style.webkitTransform="translate3d("+(a-d)+"px,"+q+"px,0px) scale3d("+
b+","+b+","+b+")"):c.zoomDiv.style.webkitTransform="translate3d("+a+"px,"+q+"px,0px) scale3d("+b+","+b+","+b+")";c.zoomDiv.style.webkitBoxShadow="";customEvents.fireEvent(START_ZOOM_PRELOADER,{shift:-d});setTimeout(function(){b>c.minZoom?customEvents.fireEvent(ZOOM_ZOOM_ANIMATION_END,{zoomFactor:f,page:c.zoomPage,startPos:r}):1===orientationObserver.getType()?customEvents.fireEvent(ZOOM_ANIMATION_END_TO_ONE,{page:c.zoomPage}):customEvents.fireEvent(ZOOM_ANIMATION_END_TO_TWO,{page:pageTable.getUserIDFromFileID(c.zoomPage)})},
180)};var d=-1,n=-1,c=this;this.touch=function(){this.slideMode=(publicationData.page[c.currentPage].wide?this.widePageWidth:this.pageWidth)>window.innerWidth?!0:!1;c.block||c.gesture||ZOOM_LOCK||c.slideMode||(d=Modernizr.touch?event.targetTouches[0].pageX:event.pageX)};this.endmove=function(){this.slideMode=(publicationData.page[c.currentPage].wide?this.widePageWidth:this.pageWidth)>window.innerWidth?!0:!1;if(!(c.block||c.gesture||ZOOM_LOCK||c.slideMode)&&(n=Modernizr.touch?event.changedTouches[0].pageX:
event.pageX,-1!=d&&-1!=n)){var a=d-n;120<a?pageMediator.right():-120>a&&pageMediator.left();n=d=-1}}};
