// Created 12/11/2013 12:56:10 PM
function Detect(){playerVersion=[0,0,0];this.ua=navigator.userAgent.toLowerCase();var l=navigator.platform.toLowerCase(),b=this.ua.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||[null,"unknown",0];if("undefined"!=typeof navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"])!(d=navigator.plugins["Shockwave Flash"].description)||"undefined"!=typeof navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin||
(plugin=!0,ie=!1,d=d.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),playerVersion[0]=parseInt(d.replace(/^(.*)\..*$/,"$1"),10),playerVersion[1]=parseInt(d.replace(/^.*\.(.*)\s.*$/,"$1"),10),playerVersion[2]=/[a-zA-Z]/.test(d)?parseInt(d.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!=typeof window.ActiveXObject)try{var g=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");g&&(d=g.GetVariable("$version"))&&(ie=!0,d=d.split(" ")[1].split(","),playerVersion=[parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],
10)])}catch(u){}this.flash=0===playerVersion[0]&&0===playerVersion[1]&&0===playerVersion[2]?!1:!0;this.flashVer=playerVersion[0]+"."+playerVersion[1]+"."+playerVersion[2];this.browser={};this.platform={};this.device={};this.features={};this.browser.name="version"==b[1]?b[3]:b[1];this.browser.name="unknown"==this.browser.name?"safari":this.browser.name;this.browser[this.browser.name]=!0;mode="ie"==b[1]&&document.documentMode;this.browser.version=mode||parseFloat("opera"==b[1]&&b[4]?b[4]:b[2]);this.platform.name=
this.ua.match(/ip(?:ad|od|hone)/)?"ios":this.ua.match(/(?:msie 9)/)?"wphone":(this.ua.match(/(?:webos|android|bada|symbian|palm|blackberry)/)||l.match(/mac|win|linux/)||["other"])[0];this.platform[this.platform.name]=!0;this.platform.version=0;this.platform.mac?(b=this.ua.match(/os\sx\s(\d+[\._]*\d*[\._]*\d*)/),this.platform.version=fbUtils.isArray(b)&&1<b.length?b[1].split(/[\._]/):0):this.platform.ios?(b=this.ua.match(/os\s(\d+_*\d*_*\d*)/),this.platform.version=fbUtils.isArray(b)&&1<b.length?b[1].split("_"):
0):this.platform.android&&(b=this.ua.match(/android\s(\d+\.*\d*\.*\d*)/),this.platform.version=fbUtils.isArray(b)&&1<b.length?b[1].split("."):0);this.platform.verCheck=function(b){return 1*this.platform.version==1*b?0:1*b>1*this.platform.version?-1:1};this.device.name=this.ua.match(/ipad/)?"ipad":this.ua.match(/ipad/)?"ipad":this.ua.match(/iphone/)?"iphone":this.ua.match(/android/)?"android":l.match(/mac|win|linux/)?"pc":"other";this.device[this.device.name]=!0;this.device.version=this.platform.version[0];
this.device.type=this.ua.match(/(mobile\ssafari)|iphone|ipod/)?"mobile":"tablet";this.device.vendor=this.ua.match(/sony/)?"sony":this.ua.match(/htc/)?"htc":this.ua.match(/samsung/)?"samsung":this.ua.match(/lg/)?"lg":this.ua.match(/apple/)?"apple":"other";this.publisher={};try{this.device.name=preview.get_Type(),this.platform.name="android"==this.device.name?"android":"ios",this.platform[this.platform.name]=!0,this.device[this.device.name]=!0,this.device.type="android"==this.platform.name?"mobile":
this.device.ipad?"tablet":"mobile",this.publisher.orientation=preview.get_Orientation(),this.publisher.isOn=!0}catch(m){}this.isBasic=this.isFlash=this.isMobile=!1;this.platform.ios||this.platform.blackberry?this.isMobile=!0:(this.platform.ios||this.platform.android)&&(this.browser.safari||this.browser.chrome)?this.isMobile=!0:this.platform.android?this.isBasic=!0:!this.device.pc&&!this.device.other||this.flash?this.isFlash=!0:this.isBasic=!0;this.isTablet="ipad"==this.device.name||3==this.device.version?
!0:!1;var a=this;this.init=function(){a.device.width=window.innerWidth;a.device.height=window.innerHeight;customEvents.addListener(ROTATE_DEVICE,function(){a.device.width=window.innerWidth;a.device.height=window.innerHeight});a.platform.android?(window.innerWidth>window.innerHeight&&(a.device.orientation="landscape"),window.innerWidth<window.innerHeight&&(a.device.orientation="portrait")):a.platform.ios?(window.innerWidth>window.innerHeight&&(a.device.orientation="landscape"),window.innerWidth<window.innerHeight&&
(a.device.orientation="portrait")):a.device.orientation=!1;a.isInit=!0}}
window.Modernizr=function(l,b,g){function u(k,c){for(var b in k){var a=k[b];if(!~(""+a).indexOf("-")&&z[a]!==g)return"pfx"==c?a:!0}return!1}function m(k,c,b){var a=k.charAt(0).toUpperCase()+k.slice(1),h=(k+" "+A.join(a+" ")+a).split(" ");if("string"===typeof c||"undefined"===typeof c)c=u(h,c);else a:{h=(k+" "+B.join(a+" ")+a).split(" "),k=h;for(var e in k)if(a=c[k[e]],a!==g){c=!1===b?k[e]:"function"===typeof a?a.bind(b||c):a;break a}c=!1}return c}var a={},q=b.documentElement,e=b.createElement("modernizr"),
z=e.style,C=" -webkit- -moz- -o- -ms- ".split(" "),A=["Webkit","Moz","O","ms"],B=["webkit","moz","o","ms"],e={},D=[],v=D.slice,s,w=function(a,c,f,e){var h,g,l,m,n=b.createElement("div"),r=b.body,p=r||b.createElement("body");if(parseInt(f,10))for(;f--;)l=b.createElement("div"),l.id=e?e[f]:"modernizr"+(f+1),n.appendChild(l);return h=['&#173;<style id="smodernizr">',a,"</style>"].join(""),n.id="modernizr",(r?n:p).innerHTML+=h,p.appendChild(n),r||(p.style.background="",p.style.overflow="hidden",m=q.style.overflow,
q.style.overflow="hidden",q.appendChild(p)),g=c(n,a),r?n.parentNode.removeChild(n):(p.parentNode.removeChild(p),q.style.overflow=m),!!g},E=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(c,f){f=f||b.createElement(a[c]||"div");c="on"+c;var e=c in f;return e||(f.setAttribute||(f=b.createElement("div")),f.setAttribute&&f.removeAttribute&&(f.setAttribute(c,""),e="function"===typeof f[c],"undefined"===typeof f[c]||(f[c]=g),
f.removeAttribute(c))),e}}(),x={}.hasOwnProperty,t;"undefined"===typeof x||"undefined"===typeof x.call?t=function(a,c){return c in a&&"undefined"===typeof a.constructor.prototype[c]}:t=function(a,c){return x.call(a,c)};Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;if("function"!=typeof c)throw new TypeError;var b=v.call(arguments,1),e=function(){if(this instanceof e){var h=function(){};h.prototype=c.prototype;var h=new h,g=c.apply(h,b.concat(v.call(arguments)));return Object(g)===
g?g:h}return c.apply(a,b.concat(v.call(arguments)))};return e});e.touch=function(){var a;return"ontouchstart"in l||l.DocumentTouch&&b instanceof DocumentTouch?a=!0:w(["@media (",C.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(c){a=9===c.offsetTop}),a};e.hashchange=function(){return E("hashchange",l)&&(b.documentMode===g||7<b.documentMode)};e.csstransforms=function(){return!!m("transform")};e.csstransforms3d=function(){var a=!!m("perspective");return a&&
"webkitPerspective"in q.style&&w("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(c,b){a=9===c.offsetLeft&&3===c.offsetHeight}),a};e.csstransitions=function(){return m("transition")};for(var y in e)t(e,y)&&(s=y.toLowerCase(),a[s]=e[y](),D.push((a[s]?"":"no-")+s));a.addTest=function(b,c){if("object"==typeof b)for(var e in b)t(b,e)&&a.addTest(e,b[e]);else{b=b.toLowerCase();if(a[b]!==g)return a;c="function"==typeof c?c():c;"undefined"!=typeof enableClasses&&
enableClasses&&(q.className+=" "+(c?"":"no-")+b);a[b]=c}return a};z.cssText="";return e=null,a._version="2.6.2",a._prefixes=C,a._domPrefixes=B,a._cssomPrefixes=A,a.hasEvent=E,a.testProp=function(a){return u([a])},a.testAllProps=m,a.testStyles=w,a}(this,this.document);
