<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="CNC replacement parts and supplies.">
    <meta name="author" content="Sari Rahal">

    <title>Nu Tek Sales</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/shop-homepage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <?php include 'nav.php'; ?>

<div style="clear:both; height:30px;"></div>
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Nu Tek Sales</p>
                <form role="form" method="get" action="<?php echo str_replace('index.php', '', $_SERVER['PHP_SELF']) . '?' . htmlspecialchars($_SERVER['QUERY_STRING']);?>">
                    <?php if (isset($_GET['p'])):?>
                        <input type="hidden" name="p" value="<?php echo htmlspecialchars($_GET['p']);?>"/>
                    <?php endif;?>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="keyword" id="searchId" placeholder="Search items" value="<?php echo isset($_GET['keyword']) ? htmlspecialchars($_GET['keyword']) : '';?>" />
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">Search</button>
                            </span>
                        </div>
                    </div>
                </form>
                <div class="list-group">
                <?php if (isset($categories) && !empty($categories)):?>
                <?php foreach ($categories as $cat):?>
                    <a href="<?php echo str_replace('index.php', '', $_SERVER['PHP_SELF']) . '?category=' . htmlspecialchars($cat['CategoryID']);?>" class="list-group-item"><?php if ($category == $cat['CategoryID']):?><strong><?php endif;?><?php echo htmlspecialchars($cat['Name']);?> (<?php echo htmlspecialchars($cat['Count']);?>)<?php if ($category == $cat['CategoryID']):?></strong><?php endif;?></a>
                <?php endforeach;?>
                <?php endif;?>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row">
                    <?php if (isset($error) && strlen($error) > 0):?>
                        <div class="alert alert-danger" role="alert"><?php echo $error;?></div>
                    <?php endif;?>

                    <?php if (isset($items) && !empty($items)):?>
                    <?php foreach ($items as $item):?>
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <a href="<?php echo $item->pictureURLSuperSize;?>"><img src="<?php echo $item->pictureURLLarge;?>" alt="<?php echo htmlspecialchars($item->title);?>" /></a>
                            <div class="caption">
                                <h5><?php echo htmlspecialchars($item->title);?></h5>
                                <h4 class="text-center">$<?php echo number_format((strval($item->listingInfo->buyItNowAvailable) === 'true' ? floatval($item->listingInfo->buyItNowPrice) : floatval($item->sellingStatus->currentPrice)), 2, '.', ',');?></h4>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
                    <?php endif;?>

                </div>

                <div><?php echo $pageNav;?></div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <?php include('footer.php'); ?>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>
